// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBDzRAofyMPm4BKRFc7LO5ScY6F2EYHM',
    appId: '1:380908941645:web:284f91735a7c12cc68c704',
    messagingSenderId: '380908941645',
    projectId: 'booking-68265',
    authDomain: 'booking-68265.firebaseapp.com',
    storageBucket: 'booking-68265.firebasestorage.app',
    measurementId: 'G-MN7VZ70B9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDegTesd3JJEs6nxJEv_Ig6ZSf2yuRjVhs',
    appId: '1:380908941645:android:0762abf24f8bb91968c704',
    messagingSenderId: '380908941645',
    projectId: 'booking-68265',
    storageBucket: 'booking-68265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv3X8ctJQv0spNC8sdgkVDa0MsVh48XXc',
    appId: '1:380908941645:ios:230985b317c3a56c68c704',
    messagingSenderId: '380908941645',
    projectId: 'booking-68265',
    storageBucket: 'booking-68265.firebasestorage.app',
    iosClientId: '380908941645-vdsa7gihrcs1m956pe1fii1fueu5drg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.remakingBookingAppTrail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv3X8ctJQv0spNC8sdgkVDa0MsVh48XXc',
    appId: '1:380908941645:ios:230985b317c3a56c68c704',
    messagingSenderId: '380908941645',
    projectId: 'booking-68265',
    storageBucket: 'booking-68265.firebasestorage.app',
    iosClientId: '380908941645-vdsa7gihrcs1m956pe1fii1fueu5drg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.remakingBookingAppTrail2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkBDzRAofyMPm4BKRFc7LO5ScY6F2EYHM',
    appId: '1:380908941645:web:cee496d52ff6b38c68c704',
    messagingSenderId: '380908941645',
    projectId: 'booking-68265',
    authDomain: 'booking-68265.firebaseapp.com',
    storageBucket: 'booking-68265.firebasestorage.app',
    measurementId: 'G-0RXQ43GBXZ',
  );

}