// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNVJXpMrmS9fn0MSlGLOnNCqfPyldpU0',
    appId: '1:305382544999:web:8344f7bd187c9acb6826c2',
    messagingSenderId: '305382544999',
    projectId: 'hanzbthalk-aa12c',
    authDomain: 'hanzbthalk-aa12c.firebaseapp.com',
    databaseURL: 'https://hanzbthalk-aa12c-default-rtdb.firebaseio.com',
    storageBucket: 'hanzbthalk-aa12c.firebasestorage.app',
    measurementId: 'G-D424PWLXPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrP74BqsliBtIgnVPTdParY8IoX6bOA1o',
    appId: '1:305382544999:android:2fc10343956bc0776826c2',
    messagingSenderId: '305382544999',
    projectId: 'hanzbthalk-aa12c',
    databaseURL: 'https://hanzbthalk-aa12c-default-rtdb.firebaseio.com',
    storageBucket: 'hanzbthalk-aa12c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr296aQ0IWbcZTzHl30iL4kJGjPQf8OEY',
    appId: '1:305382544999:ios:cdb1d920bc0bbb4e6826c2',
    messagingSenderId: '305382544999',
    projectId: 'hanzbthalk-aa12c',
    databaseURL: 'https://hanzbthalk-aa12c-default-rtdb.firebaseio.com',
    storageBucket: 'hanzbthalk-aa12c.firebasestorage.app',
    androidClientId: '305382544999-ihhmkeq2vh6pp6c0hntllhhbd2rd6n51.apps.googleusercontent.com',
    iosBundleId: 'com.example.remakingBookingAppTrail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr296aQ0IWbcZTzHl30iL4kJGjPQf8OEY',
    appId: '1:305382544999:ios:cdb1d920bc0bbb4e6826c2',
    messagingSenderId: '305382544999',
    projectId: 'hanzbthalk-aa12c',
    databaseURL: 'https://hanzbthalk-aa12c-default-rtdb.firebaseio.com',
    storageBucket: 'hanzbthalk-aa12c.firebasestorage.app',
    androidClientId: '305382544999-ihhmkeq2vh6pp6c0hntllhhbd2rd6n51.apps.googleusercontent.com',
    iosBundleId: 'com.example.remakingBookingAppTrail2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNVJXpMrmS9fn0MSlGLOnNCqfPyldpU0',
    appId: '1:305382544999:web:c2f852d501eaec406826c2',
    messagingSenderId: '305382544999',
    projectId: 'hanzbthalk-aa12c',
    authDomain: 'hanzbthalk-aa12c.firebaseapp.com',
    databaseURL: 'https://hanzbthalk-aa12c-default-rtdb.firebaseio.com',
    storageBucket: 'hanzbthalk-aa12c.firebasestorage.app',
    measurementId: 'G-YTEF144CW5',
  );

}