class AppLocalizationsAr {
  static const Map<String, String> map = {
    // Auth & User Profile
    'appName': 'هظبطهالك',
    'login': 'تسجيل دخول',
    'signup': 'إنشاء حساب',
    'welcomeBack': 'يا تلتوميت ألف أهلاً',
    'email': 'الإيميل',
    'password': 'كلمة السر',
    'fullName': 'الاسم الكامل',
    'phoneNumber': 'الموبايل',
    'forgotPassword': 'نسيت كلمة السر؟',
    'dontHaveAccount': 'معندكش حساب؟',
    'alreadyHaveAccount': 'عندك حساب بالفعل؟',
    'dontHaveAccountSignUp': 'معندكش حساب؟ سجّل دلوقتي',
    'youAlreadyHaveAccountLogin': 'عندك ؟ خش علي طول',
    'agreeToTerms': 'أوافق على الشروط والأحكام',
    'termsOfService': 'الشروط والأحكام',
    'janeDoe': 'سليمان رجب',
    'elevenDigits': '01#################',

    // Validation & Errors
    'userNotFound': 'النمرة غلط يا عماد! \n الرقم ده مش متسجل',
    'wrongPassword': 'كلمة السر غلط.',
    'emailAlreadyInUse': 'الرقم ده مش غريب عليا \n الرقم ده متسجل قبل كدة',
    'weakPassword': 'الباسورد 🤏 (ضعيف جداً)',
    'invalidEmail': 'الإيميل غلط.',
    'emailRequired': 'نسيت الايميل خلي بالك !',
    'enterValidEmail': 'اكتب إيميل صحيح',
    'passwordRequired': 'نسيت تكتب الباسورد',
    'passwordMinLength': 'الباسورد لازم يكون ٨ حروف على الأقل',
    'nameRequired': 'برجاء إدخال الاسم',
    'phoneRequired': 'برجاء إدخال الرقم',
    'fieldRequired': 'الحقل ده مطلوب',
    'invalidAmount': 'المبلغ غير صحيح',
    'amountMustBeGreater': 'المبلغ يجب أن لا يقل عن',
    'error': 'حصل خطأ',
    'failed': 'فشلت العملية',
    'routeNotFound': 'احنا في عجيبة ايه الي وداك غريبة؟',

    // OTP Verification
    'verifyNumber': 'تحقق من رقمك',
    'enterCodeSentTo': 'أدخل الكود المرسل للرقم',
    'verifyCodeBtn': 'تأكيد الكود',
    'codeSentSuccess': 'تم إرسال الكود بنجاح',
    'invalid_otp': 'الكود غلط، حاول تاني',
    'session_expired': 'وقت الكود خلص، اطلب كود جديد',

    // Home & Navigation
    'home': 'الرئيسية',
    'places': 'الأماكن',
    'search': 'بحث',
    'bookingHub': 'مركز الحجز',
    'nearby': 'قريب منك',
    'offers': 'عروض',
    'notifications': 'الإشعارات',
    'profile': 'الملف الشخصي',
    'quickActions': 'الخيارات السريعة',

    // Owner Dashboard
    'ownerDashboard': 'لوحة التحكم للمالك',
    'addNewPlace': 'ضيف مكان جديد',
    'myPlaces': 'أماكني',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirmDeletion': 'تأكيد الحذف',
    'areYouSureDelete': 'متأكد إنك عايز تحذف المكان ده؟',
    'placeDeletedSuccessfully': 'المكان اتحذف بنجاح!',
    'noPlacesFound': 'مفيش أماكن موجودة.',
    'bookingsFor': 'الحجوزات لـ',
    'bookingDeletedSuccessfully': 'الحجز اتحذف بنجاح.',
    'errorDeletingPlace': 'فشل في حذف المكان، حاول مرة تانية',
    'step_basic_info': 'المعلومات الأساسية',
    'uploadMainPhotos': 'ارفع الصور الأساسية للمكان',
    'uploadSubPlacePhoto': 'صور الملعب',
    'addField': 'إضافة ملعب جديد',
    'photoRequired': 'يا ريت تختار صورة للملعب ده',
    'pressToSelectLocation': 'اضغط لتحديد الموقع على الخريطة',
    'locationSelectedSuccess': 'تم تحديد الموقع بنجاح ✅',
    'successTitle': 'تم الحفظ بنجاح!',
    'successDesc': 'مكانك دلوقتي على الخريطة وجاهز للحجز!',
    'successButton': 'تمام',
    'errorSaving': 'حصل خطأ أثناء الحفظ: ',

    // Booking & Status
    'bookingPage': 'صفحة الحجز',
    'bookNow': 'احجز دلوقتي',
    'available': 'متاح',
    'unavailable': 'مش متاح',
    'noSlotsAvailable': 'مفيش مواعيد متاحة',
    'selectDate': 'اختار التاريخ',
    'selectTime': 'اختار الوقت',
    'selectDay': 'اختار اليوم:',
    'availableTimeSlotsFor': 'المواعيد المتاحة ليوم ',
    'confirmAndBook': 'أكد واحجز',
    'confirmBooking': 'تأكيد الحجز',
    'notAvailableShort': 'غير متاح',
    'open': 'فاتح',
    'openClose': 'الفتح: %1 - الإغلاق: %2',
    'totalAmountColon': 'إجمالي الحساب: ',
    'pleaseSelectTimeSlot': 'الرجاء اختيار وقت للحجز أولاً',
    'newBooking': 'حجز جديد لعميل',
    'customerName': 'اسم العميل',
    'selectedHours': 'الساعات المختارة',
    "myBookings": "حجوزاتي",
    "confirmed": "مؤكد",
    "pending": "قيد الانتظار",
    "cancelled": "ملغي",
    "paid": "المدفوع",
    "remaining": "المتبقي",
    "total": "الإجمالي",
    "noBookingsFound": "لا توجد حجوزات حالياً",
    "totalPaid": "إجمالي المدفوع",
    "past": "المعاد ده عدا خلاص مش هنقدر نحجزه",
    "booked": "للاسف حد سبقك و حجز",

    // PlaceModel Details
    'placeDetails': 'تفاصيل المكان',
    'description': 'الوصف',
    'category': 'التصنيف',
    'price': 'السعر',
    'noPriceAvailable': 'السعر مش متاح حالياً',
    'pricePerHour': 'سعر الساعة',
    'pricePerHourColon': 'سعر الساعة: ',
    'noPlayersInfo': 'مش عارفين كام ضد كام',
    'availableFields': 'الملاعب المتاحة',
    'viewDetails': 'شوف التفاصيل',
    'minimumCharge': 'أقل مبلغ للحجز',
    'le': 'ج.م',
    'egp': 'ج.م',
    'about': 'عن المكان',
    'placeColon': 'المكان: ',
    'sectionColon': 'القسم: ',
    'playersColon': 'اللعيبة: ',

    // Payment Logic
    'paymentSuccess': 'عملية ناجحة!',
    'paymentFailed': 'فشلت العملية',
    'bookingConfirmedSuccess':
        'تم تأكيد الحجز بنجاح، تقدر تتابع حالة طلبك من القائمة.',
    'paymentFailedMessage':
        'للأسف حصل مشكلة أثناء الدفع، حاول تاني أو تواصل معنا.',
    'confirmWalletPayment': 'تأكيد دفع المحفظة',
    'minimumDepositColon': 'الحد الأدنى المطلوب: ',
    'failedPaymentUrl': 'فشل تجهيز رابط الدفع',
    'errorProcessingPayment': 'خطأ أثناء معالجة الدفع',
    'minDeposit': 'الحد الأدنى',
    'halfPrice': 'نص السعر',
    'fullPrice': 'السعر الكامل',
    'enterPaymentAmount': 'أدخل مبلغ الدفع',
    'minimumRequiredDeposit': 'الحد الأدنى المطلوب للحجز',
    'remainingAmount': 'المبلغ المتبقي',
    'customAmount': 'مبلغ مخصص',
    'paymentAmount': 'مبلغ الدفع',
    'selectPaymentAmount': 'اختر مبلغ دفع',
    'enterAmount': 'أدخل المبلغ',
    'payNow': 'ادفع الآن',
    'payViaWallet': 'الدفع عبر المحفظة',
    'secureDigitalPayment': 'دفع رقمي آمن',
    'allPaymentsMustBeDigital': 'جميع المدفوعات يجب أن تكون رقمية',
    'selectedAmount': 'المبلغ المختار',
    'customAmountPayment': 'دفع مبلغ مخصص',

    // Categories
    'Football': 'كرة قدم',
    'PlayStation': 'بلايستيشن',
    'Cafe': 'كافيه / مطعم',
    'Padel': 'بادل',

    // Week Days & Time
    'monday': 'الاثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    'sunday': 'الأحد',
    'day': 'اليوم',
    'hour_singular': 'ساعة',
    'hour_plural': 'ساعات',
    'summary_consecutive': 'انت حجزت {} {} من الساعة {}:00 للساعة {}:00 يوم {}',
    'summary_separate': 'انت حجزت {} ساعات منفصلة يوم {}:',
    'slot_prefix': '• الساعة {}: من {}:00 لـ {}:00',

    // UI Actions
    'loading': 'جارِ التحميل...',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'ok': 'تمام',
    'save': 'حفظ',
    'logout': 'تسجيل خروج',
    'noData': 'مفيش بيانات.',
    'successMessage': 'تمت العملية بنجاح',
    'gallery': 'المعرض',
    'camera': 'الكاميرا',

    "past_status": "انتهى",
    "booked_by_app": "حجز بواسطة التطبيق",
    "booked_by_you": "حجزك أنت",
    "available_status": "متاح",
    "msg_time_started": "هذا الموعد قد بدأ بالفعل",
    "msg_already_booked": "عذراً، هذا الموعد محجوز مسبقاً",

    "business_dashboard": "لوحة تحكم النشاط",
    "showing_data_from": "عرض البيانات من",
    "to": "إلى",
    "total_revenue_gross": "إجمالي الإيرادات",
    "app_deposits": "عربون التطبيق",
    "money_held_by_app": "مبالغ في محفظة الأبلكيشن",
    "app_work": "شغل الأبلكيشن",
    "hours_from_users": "ساعات محجوزة من المستخدمين",
    "manual_revenue": "إيراد يدوي",
    "cash_collected_by_you": "كاش استلمته يدويًا",
    "resv_count": "عدد الحجوزات",
    "app_vs_manual": "التطبيق / يدوي",
    "usage_performance": "أداء الإشغال",
    "total_op_hours_desc": "إجمالي ساعات التشغيل في الفترة",
    "hrs_unit": " ساعة",

    // Missing keys added during localization audit
    "originalTotal": "الإجمالي الأصلي",
    "phoneInvalid": "رقم الهاتف غير صحيح",
    "place_not_found": "المكان غير موجود",
    "Pleaseenteryour": "يرجى إدخال",
    "remainingForField": "المتبقي للحقل",
    "requiredNow": "مطلوب الآن",
    "resendAvailable": "إعادة الإرسال متاحة",
    "resendCode": "إعادة إرسال الكود",
    "resendIn": "إعادة الإرسال خلال",
    "revenue_split": "تقسيم الإيرادات",
    "Signuptounlockallbookingopportunities.": "سجل لفتح جميع فرص الحجز.",
    "total_money__by_app": "إجمالي المال بواسطة التطبيق",
    "usePoints": "استخدام النقاط",
    "using": "استخدام",
    "viewOnMap": "عرض على الخريطة",
    "willBepaid": "سيتم الدفع",
    "YouAlreadyHaveAccount? Log In": "عندك حساب بالفعل؟ سجل دخول",
    "confirmAccount": "بناكد الحساب",
  };
}
