class AppLocalizationsEn {
  static const Map<String, String> map = {
    // Auth & User Profile
    'appName': 'Hanzbthalk', // تأكد من السبيلنج الصحيح للاسم
    'login': 'Login',
    'signup': 'Sign Up',
    'welcomeBack': 'Welcome back!',
    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full Name',
    'phoneNumber': 'Phone Number',
    'forgotPassword': 'Forgot Password?',
    'dontHaveAccount': 'Don\'t have an account?',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccountSignUp': 'Don\'t have an account? Sign Up',
    'youAlreadyHaveAccountLogin': 'Already have an account? Log In',
    'agreeToTerms': 'I agree to the Terms of Service',
    'termsOfService': 'Terms of Service',
    'janeDoe': 'Jane Doe',
    'elevenDigits': '01#########',

    // Validation & Errors
    'userNotFound': 'No user found for that email.',
    'wrongPassword': 'Wrong password provided.',
    'emailAlreadyInUse': 'The email address is already in use.',
    'weakPassword': 'The password provided is too weak.',
    'invalidEmail': 'The email address is not valid.',
    'emailRequired': 'Email is required',
    'enterValidEmail': 'Enter a valid email',
    'passwordRequired': 'Password is required',
    'passwordMinLength': 'Password must be at least 8 characters',
    'nameRequired': 'Please enter your name',
    'phoneRequired': 'Please enter your phone number',
    'fieldRequired': 'This field is required',
    'invalidAmount': 'Invalid amount',
    'amountMustBeGreater': 'Amount must be at least',
    'error': 'Error',
    'failed': 'Failed',
    'routeNotFound': 'Route Not Found',

    // OTP Verification
    'verifyNumber': 'Verify Your Number',
    'enterCodeSentTo': 'Enter the code sent to',
    'verifyCodeBtn': 'Verify Code',
    'codeSentSuccess': 'Code sent successfully',
    'invalid_otp': 'Invalid code, please try again',
    'session_expired': 'Session expired, request a new code',

    // Home & Navigation
    'home': 'Home',
    'places': 'Places',
    'search': 'Search',
    'bookingHub': 'Booking Hub',
    'nearby': 'Near By',
    'offers': 'Offers',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'quickActions': 'Quick Actions',

    // Owner Dashboard
    'ownerDashboard': 'Owner Dashboard',
    'addNewPlace': 'Add New Place',
    'myPlaces': 'My Places',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirmDeletion': 'Confirm Deletion',
    'areYouSureDelete': 'Are you sure you want to delete',
    'placeDeletedSuccessfully': 'Place deleted successfully!',
    'noPlacesFound': 'No places found.',
    'bookingsFor': 'Bookings for',
    'bookingDeletedSuccessfully': 'Booking deleted successfully.',
    'errorDeletingPlace': 'Failed to delete place. Please try again.',
    'step_basic_info': 'Basic Information',
    'uploadMainPhotos': 'Upload Main Photos',
    'uploadSubPlacePhoto': 'Upload Field Photo',
    'addField': 'Add New Field',
    'photoRequired': 'Please add a photo for this field',
    'pressToSelectLocation': 'Press to select location on map',
    'locationSelectedSuccess': 'Location selected successfully ✅',
    'successTitle': 'Saved Successfully!',
    'successDesc': 'Your PlaceModel is now on the map and ready for booking!',
    'successButton': 'Done',
    'errorSaving': 'Error occurred while saving: ',

    // Booking & Status
    'bookingPage': 'Booking Page',
    'bookNow': 'Book Now',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'noSlotsAvailable': 'No slots available',
    'selectDate': 'Select Date',
    'selectTime': 'Select Time',
    'selectDay': 'Select Day:',
    'availableTimeSlotsFor': 'Available Time Slots for ',
    'confirmAndBook': 'Confirm and Book',
    'confirmBooking': 'Confirm Booking',
    'notAvailableShort': 'N/A',
    'open': 'Open',
    'openClose': 'Open: %1 - Close: %2',
    'totalAmountColon': 'Total Amount: ',
    'pleaseSelectTimeSlot': 'Please select a time slot first',
    'newBooking': 'New Booking for Customer',
    'customerName': 'Customer Name',
    'selectedHours': 'Selected Hours',
    "myBookings": "My Bookings",
    "confirmed": "Confirmed",
    "pending": "Pending",
    "cancelled": "Cancelled",
    "paid": "Paid",
    "remaining": "Remaining",
    "total": "Total",
    "noBookingsFound": "No bookings found yet",
    "totalPaid": "Total Paid",
    "past": "this time has already passed, we can't book it",
    "booked": "sorry, someone else has booked this slot",

    // PlaceModel Details
    'placeDetails': 'Place Details',
    'description': 'Description',
    'category': 'Category',
    'price': 'Price',
    'noPriceAvailable': 'No price available',
    'pricePerHour': 'Price per Hour',
    'pricePerHourColon': 'Price per Hour: ',
    'noPlayersInfo': 'No players info',
    'availableFields': 'Available fields',
    'viewDetails': 'View Details',
    'minimumCharge': 'Minimum Charge',
    'le': 'LE',
    'egp': 'LE',
    'about': 'About',
    'placeColon': 'Place: ',
    'sectionColon': 'Section: ',
    'playersColon': 'Players: ',

    // Payment Logic
    'paymentSuccess': 'Payment Successful!',
    'paymentFailed': 'Payment Failed',
    'bookingConfirmedSuccess':
        'Booking confirmed successfully! You can track your order status from the menu.',
    'paymentFailedMessage':
        'Unfortunately, there was an issue with your payment. Please try again or contact us.',
    'confirmWalletPayment': 'Confirm Wallet Payment',
    'minimumDepositColon': 'Minimum Deposit Required: ',
    'failedPaymentUrl': 'Failed to prepare payment link',
    'errorProcessingPayment': 'Error processing payment',
    'minDeposit': 'Minimum',
    'halfPrice': 'Half Price',
    'fullPrice': 'Full Price',
    'enterPaymentAmount': 'Enter payment amount',
    'minimumRequiredDeposit': 'Minimum required deposit for booking',
    'remainingAmount': 'Remaining Amount',
    'customAmount': 'Custom Amount',
    'paymentAmount': 'Payment Amount',
    'selectPaymentAmount': 'Select payment amount',
    'enterAmount': 'Enter amount',
    'payNow': 'Pay Now',
    'payViaWallet': 'Pay via Wallet',
    'secureDigitalPayment': 'Secure Digital Payment',
    'allPaymentsMustBeDigital': 'All payments must be made digitally',
    'selectedAmount': 'Selected Amount',
    'customAmountPayment': 'Custom Amount Payment',

    // Categories
    'Football': 'Football',
    'PlayStation': 'PlayStation',
    'Cafe': 'Cafe',
    'Padel': 'Padel',

    // Week Days & Time
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'day': 'Day',
    'hour_singular': 'hour',
    'hour_plural': 'hours',
    'summary_consecutive': 'You booked {} {} from {}:00 to {}:00 on {}',
    'summary_separate': 'You booked {} separate hours on {}:',
    'slot_prefix': 'Slot {}: From {}:00 to {}:00',

    // UI Actions
    'loading': 'Loading...',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'ok': 'OK',
    'save': 'Save',
    'logout': 'Logout',
    'noData': 'No data available.',
    'successMessage': 'Operation completed successfully',

    "past_status": "Ended",
    "booked_by_app": "Booked by the app",
    "booked_by_you": "Booked by you",
    "available_status": "Available",
    "msg_time_started": "This time has already started",
    "msg_already_booked": "Sorry, this slot is already booked",
  };
}
