class AppLocalizationsAr {
  static const Map<String, String> map = {
    // Auth & User Profile
    'appName': 'هنظبطهالك',
    'version': 'الإصدار',
    'login': 'تسجيل دخول',
    'signup': 'إنشاء حساب',
    'welcomeBack': 'يا تلتوميت ألف أهلاً',
    'email': 'الإيميل',
    'password': 'كلمة السر',
    'fullName': 'الاسم الكامل',
    'phoneNumber': 'الموبايل',
    'forgotPassword': 'نسيت كلمة السر؟',
    'dontHaveAccount': 'معندكش حساب؟',
    'alreadyHaveAccount': 'عندك حساب بالفعل؟',
    'dontHaveAccountSignUp': 'معندكش حساب؟ سجّل دلوقتي',
    'youAlreadyHaveAccountLogin': 'عندك حساب بالفعل؟ سجل دخول',
    'visitWebsite': 'زيارة موقعنا الإلكتروني',
    'nameTooShort': 'الاسم يجب أن يكون حرفين على الأقل',
    'iAgreeTo': 'أوافق على',
    'privacyPolicyAndTerms': 'سياسة الخصوصية والشروط والأحكام',
    'mustAgreeToPolicies':
        'يجب عليك الموافقة على سياسة الخصوصية والشروط لإنشاء الحساب',
    'agreeToTerms': 'أوافق على الشروط والأحكام',
    'termsOfService': 'الشروط والأحكام',
    'janeDoe': 'سليمان رجب',
    'elevenDigits': '01#################',
    'lowestprice': 'الاقل سعر ',

    // Validation & Errors
    'userNotFound': 'النمرة غلط يا عماد! \n الرقم ده مش متسجل',
    'wrongPassword': 'كلمة السر غلط.',
    'phoneNumberAlreadyExists':
        'الرقم ده مش غريب عليا \n الرقم ده متسجل قبل كدة',
    'weakPassword': 'الباسورد 🤏 (ضعيف جداً)',
    'invalidEmail': 'الإيميل غلط.',
    'emailRequired': 'نسيت الايميل خلي بالك !',
    'enterValidEmail': 'اكتب إيميل صحيح',
    'passwordRequired': 'نسيت تكتب الباسورد',
    'passwordMinLength': 'الباسورد لازم يكون ٨ حروف على الأقل',
    'nameRequired': 'برجاء إدخال الاسم',
    'phoneRequired': 'برجاء إدخال الرقم',
    'fieldRequired': 'الحقل ده مطلوب',
    'invalidAmount': 'المبلغ غير صحيح',
    'amountMustBeGreater': 'المبلغ يجب أن لا يقل عن',
    'error': 'حصل خطأ',
    'failed': 'فشلت العملية',
    'routeNotFound': 'احنا في عجيبة ايه الي وداك غريبة؟',

    // OTP Verification
    'verifyNumber': 'تحقق من رقمك',
    'enterCodeSentTo': 'أدخل الكود المرسل للرقم',
    'verifyCodeBtn': 'تأكيد الكود',
    'codeSentSuccess': 'تم إرسال الكود بنجاح',
    'invalid_otp': 'الكود غلط، حاول تاني',
    'session_expired': 'وقت الكود خلص، اطلب كود جديد',

    // Home & Navigation
    'home': 'الرئيسية',
    'places': 'الأماكن',
    'search': 'بحث',
    'bookingHub': 'مركز الحجز',
    'nearby': 'قريب منك',
    'offers': 'عروض',
    'offer': 'عرض',
    'notifications': 'الإشعارات',
    'profile': 'الملف الشخصي',
    'quickActions': 'الخيارات السريعة',

    // Owner Dashboard
    'ownerDashboard': 'لوحة التحكم للمالك',
    'addNewPlace': 'ضيف مكان جديد',
    'myPlaces': 'أماكني',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirmDeletion': 'تأكيد الحذف',
    'areYouSureDelete': 'متأكد إنك عايز تحذف المكان ده؟',
    'placeDeletedSuccessfully': 'المكان اتحذف بنجاح!',
    'noPlacesFound': 'مفيش أماكن موجودة.',
    'bookingsFor': 'الحجوزات لـ',
    'bookingDeletedSuccessfully': 'الحجز اتحذف بنجاح.',
    'errorDeletingPlace': 'فشل في حذف المكان، حاول مرة تانية',
    'step_basic_info': 'المعلومات الأساسية',
    'uploadMainPhotos': 'ارفع الصور الأساسية للمكان',
    'uploadSubPlacePhoto': 'صور الملعب',
    'addField': 'إضافة ملعب جديد',
    'photoRequired': 'يا ريت تختار صورة للملعب ده',
    'pressToSelectLocation': 'اضغط لتحديد الموقع على الخريطة',
    'locationSelectedSuccess': 'تم تحديد الموقع بنجاح ✅',
    'successTitle': 'تم الحفظ بنجاح!',
    'successDesc': 'مكانك دلوقتي على الخريطة وجاهز للحجز!',
    'successButton': 'تمام',
    'errorSaving': 'حصل خطأ أثناء الحفظ: ',

    // Booking & Status
    'bookingPage': 'صفحة الحجز',
    'bookNow': 'احجز دلوقتي',
    'available': 'متاح',
    'unavailable': 'مش متاح',
    'noSlotsAvailable': 'مفيش مواعيد متاحة',
    'selectDate': 'اختار التاريخ',
    'selectTime': 'اختار الوقت',
    'selectDay': 'اختار اليوم:',
    'availableTimeSlotsFor': 'المواعيد المتاحة ليوم ',
    'confirmAndBook': 'أكد واحجز',
    'confirmBooking': 'تأكيد الحجز',
    'notAvailableShort': 'غير متاح',
    'placePlaceholder': 'مكان',
    'orderIdLabel': 'رقم الطلب: #',
    'open': 'فاتح',
    'openClose': 'الفتح: %1 - الإغلاق: %2',
    'totalAmountColon': 'إجمالي الحساب: ',
    'pleaseSelectTimeSlot': 'الرجاء اختيار وقت للحجز أولاً',
    'newBooking': 'حجز جديد لعميل',
    'customerName': 'اسم العميل',
    'selectedHours': 'الساعات المختارة',
    "myBookings": "حجوزاتي",
    "confirmed": "مؤكد",
    "pending": "قيد الانتظار",
    "cancelled": "ملغي",
    "paid": "المدفوع",
    "remaining": "المتبقي",
    "total": "الإجمالي",
    "noBookingsFound": "لا توجد حجوزات",
    "noBookingsSubtitle":
        "لم تقم بحجز أي ملاعب أو مباريات بعد. ابدأ في استكشاف الملاعب واحجز مكانك الآن!",
    "exploreNow": "استكشف الآن",
    "rebook": "احجز مجدداً",
    "fullyPaid": "مدفوع بالكامل",
    "depositPaid": "عربون مدفوع",
    "totalPaid": "إجمالي المدفوع",
    "past": "المعاد ده عدا خلاص مش هنقدر نحجزه",
    "booked": "للاسف حد سبقك و حجز",

    // PlaceModel Details
    'placeDetails': 'تفاصيل المكان',
    'description': 'الوصف',
    'category': 'التصنيف',
    'price': 'السعر',
    'noPriceAvailable': 'السعر مش متاح حالياً',
    'pricePerHour': 'سعر الساعة',
    'pricePerHourColon': 'سعر الساعة: ',
    'noPlayersInfo': 'مش عارفين كام ضد كام',
    'availableFields': 'الملاعب المتاحة',
    'viewDetails': 'شوف التفاصيل',
    'minimumCharge': 'أقل مبلغ للحجز',
    'le': 'ج.م',
    'egp': 'ج.م',
    'about': 'عن المكان',
    'placeColon': 'المكان: ',
    'sectionColon': 'القسم: ',
    'playersColon': 'اللعيبة: ',

    // Payment Logic
    'paymentSuccess': 'عملية ناجحة!',
    'paymentFailed': 'فشلت العملية',
    'bookingConfirmedSuccess':
        'تم تأكيد الحجز بنجاح، تقدر تتابع حالة طلبك من القائمة.',
    'paymentFailedMessage':
        'للأسف حصل مشكلة أثناء الدفع، حاول تاني أو تواصل معنا.',
    'confirmWalletPayment': 'تأكيد دفع المحفظة',
    'minimumDepositColon': 'الحد الأدنى المطلوب: ',
    'failedPaymentUrl': 'فشل تجهيز رابط الدفع',
    'errorProcessingPayment': 'خطأ أثناء معالجة الدفع',
    'minDeposit': 'الحد الأدنى',
    'halfPrice': 'نص السعر',
    'fullPrice': 'السعر الكامل',
    'enterPaymentAmount': 'أدخل مبلغ الدفع',
    'minimumRequiredDeposit': 'الحد الأدنى المطلوب للحجز',
    'remainingAmount': 'المبلغ المتبقي',
    'customAmount': 'مبلغ مخصص',
    'paymentAmount': 'مبلغ الدفع',
    'selectPaymentAmount': 'اختر مبلغ دفع',
    'enterAmount': 'أدخل المبلغ',
    'payNow': 'ادفع الآن',
    'payViaWallet': 'الدفع عبر المحفظة',
    'secureDigitalPayment': 'دفع رقمي آمن',
    'allPaymentsMustBeDigital': 'جميع المدفوعات يجب أن تكون رقمية',
    'selectedAmount': 'المبلغ المختار',
    'customAmountPayment': 'دفع مبلغ مخصص',

    // Categories
    'all': 'الكل',
    'football': 'كرة قدم',
    'padel': 'بادل',
    'playstation': 'بلايستيشن',
    'cafe': 'كافيه / مطعم',
    'noPlacesInCategory': 'لا توجد أماكن في هذه الفئة حالياً',
    'Football': 'كرة قدم',
    'PlayStation': 'بلايستيشن',
    'Cafe': 'كافيه / مطعم',
    'Padel': 'بادل',

    // Week Days & Time
    'monday': 'الاثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    'sunday': 'الأحد',
    'day': 'اليوم',
    'hour_singular': 'ساعة',
    'hour_plural': 'ساعات',
    'durationLabel': 'مدة الحجز',
    'summary_consecutive': 'انت حجزت {} {} من الساعة {}:00 للساعة {}:00 يوم {}',
    'summary_separate': 'انت حجزت {} ساعات منفصلة يوم {}:',
    'slot_prefix': '• الساعة {}: من {}:00 لـ {}:00',

    // UI Actions
    'loading': 'جارِ التحميل...',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'ok': 'تمام',
    'save': 'حفظ',
    'logout': 'تسجيل خروج',
    'noData': 'مفيش بيانات.',
    'successMessage': 'تمت العملية بنجاح',
    'gallery': 'المعرض',
    'camera': 'الكاميرا',

    "past_status": "انتهى",
    "booked_by_app": "حجز بواسطة التطبيق",
    "booked_by_you": "حجزك أنت",
    "available_status": "متاح",
    "msg_time_started": "هذا الموعد قد بدأ بالفعل",
    "msg_already_booked": "عذراً، هذا الموعد محجوز مسبقاً",

    "business_dashboard": "لوحة تحكم النشاط",
    "showing_data_from": "عرض البيانات من",
    "to": "إلى",
    "total_revenue_gross": "إجمالي الإيرادات",
    "app_deposits": "عربون التطبيق",
    "money_held_by_app": "مبالغ في محفظة الأبلكيشن",
    "app_work": "شغل الأبلكيشن",
    "hours_from_users": "ساعات محجوزة من المستخدمين",
    "manual_revenue": "إيراد يدوي",
    "cash_collected_by_you": "كاش استلمته يدويًا",
    "resv_count": "عدد الحجوزات",
    "app_vs_manual": "التطبيق / يدوي",
    "usage_performance": "أداء الإشغال",
    "total_op_hours_desc": "إجمالي ساعات التشغيل في الفترة",
    "hrs_unit": " ساعة",

    // Missing keys added during localization audit
    "originalTotal": "الإجمالي الأصلي",
    "phoneInvalid": "الرقم ده ناقص",
    "place_not_found": "المكان غير موجود",
    "Pleaseenteryour": "يرجى إدخال",
    "remainingForField": "المتبقي للحقل",
    "requiredNow": "مطلوب الآن",
    "resendAvailable": "إعادة الإرسال متاحة",
    "resendCode": "إعادة إرسال الكود",
    "resendIn": "إعادة الإرسال خلال",
    "revenue_split": "تقسيم الإيرادات",
    "Signuptounlockallbookingopportunities.": "سجل لفتح جميع فرص الحجز.",
    "total_money__by_app": "إجمالي المال بواسطة التطبيق",
    "usePoints": "استخدام النقاط",
    "using": "استخدام",
    "viewOnMap": "عرض على الخريطة",
    "linkCopied": "تم نسخ رابط المكان إلى الحافظة!",
    "openStatus": "مفتوح الآن",
    "closedStatus": "مغلق حالياً",
    "willBepaid": "سيتم الدفع",
    "YouAlreadyHaveAccount? Log In": "عندك حساب بالفعل؟ سجل دخول",
    "confirmAccount": "بناكد الحساب",

    // Owner Onboarding
    "owner_intro_title": "شروط وسياسات المالك",
    "owner_intro_rules":
        "يرجى قراءة وفهم السياسات التالية:\n\n1. يجب أن تكون جميع معلومات الأماكن المسجلة صحيحة ودقيقة.\n2. يجب إدارة إلغاء الحجوزات وفقاً للتوجيهات المحددة.\n3. تتم معالجة المدفوعات الرقمية بشكل آمن من خلال المنصة.",
    "owner_agree_button": "أوافق على الشروط والأحكام",
    "owner_decline": "رفض",
    "owner_continue": "استمرار",
    "owner_pending_message":
        "حسابك حالياً في حالة مالك محدود (المالك ب).\n\nيمكنك تصفح الأماكن، ولكن لا يمكنك إضافة أو تعديل أي مكان حتى توافق على الشروط والأحكام.",

    // Catchy Map & Time Search Filter
    "catchyFilterTitle": "عندك خطة؟ هنظبطهالك حالا ⚡",
    "catchyFilterSubtitle": "اختار اليوم والوقت هنظبطلك كل الملاعب المتاحة",
    "smartFilterActiveTitle": "بنظبطهالك 😉....",
    "near": "بالقرب من",
    "filteredByAreaTime": "مظبوط حسب الموقع والساعات",
    "tryItBtn": "جربها!",
    "selectAreaLabel": "اختر المنطقة",
    "filterPlacesTitle": "معايير المنطقة والوقت",
    "filterPlacesSubtitle": "اعثر على الأماكن التي تطابق احتياجاتك المحددة",
    "searchRadiusLabel": "نطاق البحث",
    "chooseLocationOnMap": "اختر الموقع على الخريطة...",

    // Interactive Onboarding Guide
    "guide_skip": "انجزز",
    "guide_next": "ياعم عدي",
    "guide_back": "ارجعلي يابني",
    "guide_finish": "انطر ابلكاش",
    "replayGuide": "تعالي اخدك لفة ",
    "guide_welcome_title": "هنا هنظبطهالك ⚡",
    "guide_welcome_desc":
        "تعال ناخد لفة سريعة نعرفك فيها إزاي تلاقي وتحجز ملعبك المفضل في ثواني!",
    "guide_logo_title": "👑",
    "guide_logo_desc": "المكان و الوقت الي انت عايزه بالسعر الي انت  عايزه 😊",
    "guide_menu_title": "الإعدادات والحساب ⚙️",
    "guide_menu_desc": "اضغط هنا عشان تدخل على حسابك، تغير اللغة.",
    "guide_bookings_title": " شوف حجوزاتك 📅",
    "guide_bookings_desc":
        "تقدر تدخل على كل حجوزاتك الحالية أو السابقة بضغطة واحدة هنا، وتعمل إعادة حجز لملعبك المفضل بسهولة.",
    "guide_search_title": " دور علي اسم المكان🔍",
    "guide_search_desc":
        "اكتب اسم أو موقع أي ملعب أو مكان وهيظهرلك فوراً في ثواني معدودة.",
    "guide_filters_title": "اختار الي انت عايزه و متشلش هم⚡",
    "guide_filters_desc":
        "اضغط هنا عشان تدور بالخريطة، تحدد المسافة المناسبة ليك، اليوم، ومدة الحجز اللي عاوزها بالظبط واحنا هنظبطهالك .",
    "guide_categories_title": "لوحة الخطط التكتيكية ⚽",
    "guide_categories_desc":
        "اختار الفئة اللي حاببها، وهتلاقي خلفية التطبيق بتترسم تلقائياً بخطة الملعب المناسبة للي اخترته!",
    "guide_tabs_title": "تبويب الفرز السريع 📑",
    "guide_tabs_desc":
        "تقدر تتنقل بين الملاعب القريبة منك، العروض المميزة، أو الأقل سعراً عشان ترتب الملاعب حسب رغبتك فوراً!",
    "guide_firstCard_title": "احجز في ثواني! ⚡",
    "guide_firstCard_desc":
        "اضغط على أي كارت ملعب عشان تشوف الصور وتفاصيل الأسعار، وتعرف المواعيد الفاضية وتحجز فوراً!",
    "statistics": "الإحصائيات",
    "fields": "ملاعب",
    "calendarSchedule": "جدول المواعيد",
    "chooseBookingDate": "اضغط عشان تختار اليوم...",
    "clearBtn": "مسح",
    "fromTimeLabel": "من",
    "searchBtn": "ظبطها",
    "targetDateLabel": "📅 حابب تلعب امتى؟",
    "timeRangeLabel": "🕐 الوقت المناسب ليك؟",
    "tooManyRequests":
        "براحة شوية! 🛑\nعملت محاولات كتير ورا بعض. استنى 15 دقيقة كدة وجرب تاني.",
    "tooManyRequestsBlock":
        "إرسال الكود مقفول بسبب محاولات كتير. جرب كمان شوية.",
    "noImage": "مفيش صورة",
    "subplace_not_found": "الملعب أو القسم غير موجود",
    "no_schedule_available": "لا يوجد جدول مواعيد لهذا الملعب!",
    "schedule_not_found": "جدول المواعيد غير موجود!",
    "user_not_authenticated": "المستخدم غير مسجل دخول",
    "unknownPlace": "مكان غير معروف",
    "error_fetching_bookings": "خطأ أثناء جلب الحجوزات",
    "failed_to_update_points": "فشل في تحديث النقاط",
    "failed_to_save_place": "فشل في حفظ بيانات المكان",
    "failed_to_update_place": "فشل في تحديث بيانات المكان",
    "failed_to_delete_place": "فشل في حذف المكان بالكامل",
    "failed_to_update_place_subplaces":
        "فشل في تحديث بيانات المكان والأماكن الفرعية",
    "error_fetching_data": "حدث خطأ أثناء جلب البيانات.",
    "failed_to_add_place": "فشل إضافة المكان.",
    "failed_to_update_data": "فشل تحديث البيانات.",
    "failed_to_load_analytics": "فشل تحميل التحليلات.",
    "failed_to_book_slots": "فشل تنفيذ عملية الحجز.",
    "failed_to_fetch_your_places": "فشل في جلب الأماكن الخاصة بك.",
    "failed_to_load_global_dashboard": "فشل في جلب بيانات لوحة التحكم العالمية",
    "old_version_not_found_to_edit": "النسخة القديمة غير موجودة لتعديلها",
    "otpSendError": "مش عارفين نبعت كود التحقق. اتأكد من النت وحاول تاني.",
    "otpSessionExpired": "وقت الجلسة انتهى. اطلب كود تحقق جديد.",
    "otpError": "الكود اللي دخلته غلط أو صلاحيته انتهت. حاول تاني.",
    'global_dashboard_title': 'لوحة تحكم الملاعب',
    'total_income': 'إجمالي الدخل',
    'total_bookings': 'إجمالي الحجوزات',
    'bookings_count_unit': 'حجز',
    'places_performance_comparison': 'مقارنة أداء الملاعب',
    'place_name_label': 'الاسم',
    'bookings_this_month': 'حجز هذا الشهر',
    'cancellation_mode_active': 'وضع الإلغاء نشط',
    'clear_selection': 'إلغاء التحديد',
    'cancel_bookings': 'إلغاء الحجوزات',
    'manual_booking': 'حجز يدوي',
    'hour_selected_singular': 'ساعة محددة',
    'hours_selected_plural': 'ساعات محددة',
    'manage_bookings_and_fields': 'إدارة الحجوزات والملاعب',
    'field_label': 'ملعب',
    'chart_app_legend': 'التطبيق',
    'chart_manual_legend': 'يدوي',

    "viewBookings": "عرض الحجوزات",
    "createManualBooking": "إنشاء حجز يدوي",
    "cancelBooking": "إلغاء الحجوزات",
    "manageAvailability": "إدارة المواعيد المتاحة",
    "editPlaceInfo": "تعديل بيانات الملعب",
    "viewAnalytics": "عرض التقارير والتحليلات",
    "manageEmployees": "إدارة الموظفين",
    "managePlaces": "إدارة الملاعب",
    "searchByPhoneHint": "ابحث برقم الموبايل",
    "currentEmployeesTitle": "الموظفين الحاليين",
    "searchResultsTitle": "نتائج البحث",
    "noEmployeesFound": "لا يوجد موظفين",
    "manageEmployeesTitle": "إدارة الموظفين",
    "edit_employee_dialog_assigned_places": "تعيين ملعب للموظف",
    "permissions": "الصلاحيات",
  };
}
