class AppLocalizationsEn {
  static const Map<String, String> map = {
    'userNotFound': 'Wrong number, chief 😅\nNever seen this one before.',
    'wrongPassword': 'Nope 😬 ... that password ain’t it.',
    'emailAlreadyInUse':
        'Hold up 🤨\nThis email is already hanging around here.',
    'weakPassword': 'That password is built like wet cardboard 🤏',
    'invalidEmail': 'That email looks suspicious 🤨',
    'emailRequired': 'You forgot the email, legend.',
    'passwordRequired': 'Password? Kinda important 😅',
    'passwordMinLength': 'Give me at least 8 characters, don’t be stingy.',
    'routeNotFound': 'Bro... how did you even get here? 💀',

    'codeSentSuccess': 'Boom 💥 Code sent.',
    'invalid_otp': 'That code is more wrong than a weather forecast.',
    'session_expired': 'Too slow, my friend ⏳ Grab a new code.',

    'nearby': 'Around the corner',
    'quickActions': 'Quick Moves ⚡',

    'placeDeletedSuccessfully': 'Poof ✨ Gone.',
    'noPlacesFound': 'We looked everywhere... nothing 😭',
    'errorDeletingPlace': 'Well... that didn’t work. Try again.',

    'locationSelectedSuccess': 'Nailed it 📍',
    'successTitle': 'All Set! 🎉',
    'successDesc': 'Your place is officially on the map. Time to make money 💰',
    'successButton': 'Let’s Go',

    'bookNow': 'Book It 🔥',
    'available': 'Ready To Go ✅',
    'unavailable': 'No Chance ❌',
    'noSlotsAvailable': 'Nothing free right now 😭',
    'pleaseSelectTimeSlot': 'Pick a time first, wizard 🧙',

    'past': 'That ship has sailed ⛵',
    'booked': 'Too late 😅 Somebody beat you to it.',

    'paymentSuccess': 'Money received 🤑',
    'paymentFailed': 'Money said "nah" 💸',
    'paymentFailedMessage':
        'Something went sideways during payment. Give it another shot.',

    'payNow': 'Pay Up 💳',
    'secureDigitalPayment': 'Fort Knox level secure 🔒',

    'noPlacesInCategory': 'Looks empty around here 👀',

    'loading': 'Cooking something up... 🍳',
    'logout': 'I’m Out ✌️',
    'successMessage': 'Mission Accomplished ✅',

    'phoneInvalid': 'That phone number looks unfinished 🤨',
    'place_not_found': 'We searched high and low. Nothing there.',
    'linkCopied': 'Link copied. Go spam your friends 😎',

    'owner_intro_title': 'The Boss Rules 😎',
    'owner_intro_rules':
        'Please read and understand the following policies:\n\n1. All registered place information must be correct and accurate.\n2. Cancellation of bookings must be managed according to specific guidelines.\n3. Digital payments are processed securely through the platform.',
    'owner_agree_button': 'Yep, I’m In',
    'owner_decline': 'Nah, Not Today',
    'owner_continue': 'Keep Rolling',

    'owner_pending_message':
        'You’re in Owner Lite mode 😅\nBrowse all you want, but no creating places until you sign the papers.',

    'catchyFilterTitle': 'Got a plan? We got you 😎⚡',
    'catchyFilterSubtitle':
        'Pick a day and time... we’ll do the detective work 🕵️',

    'smartFilterActiveTitle': 'Hold tight... we’re cooking 🍳',

    'tryItBtn': 'Hit It 🚀',

    'guide_skip': 'Skip The Boring Stuff 😴',
    'guide_next': 'Keep Going 👉',
    'guide_back': 'Take Me Back 👈',
    'guide_finish': 'Let’s Roll 🚀',

    'guide_welcome_title': 'Welcome to Hanzbthalk ⚡',
    'guide_welcome_desc':
        'A super quick tour, and then you’re off booking like a pro.',

    'guide_logo_desc': 'The place, the time, the price. No drama. 😎',

    'guide_menu_desc':
        'Your account, settings, and all the important buttons live here.',

    'guide_filters_title':
        'Tell us what you want, we’ll handle the headache 😌',

    'guide_firstCard_title': 'Book in Seconds ⚡',
    'guide_firstCard_desc':
        'Tap to view prices and book slots instantly! Bookings are Active post-payment. For cash remaining balances, generate a secure 4-digit PIN to show the owner at the field.',
    // Auth & User Profile
    'appName': 'Hanzbthalk', // تأكد من السبيلنج الصحيح للاسم
    'version': 'Version',
    'login': 'Login',
    'signup': 'Sign Up',
    'welcomeBack': 'Look who’s back 👀',

    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full Name',
    'phoneNumber': 'Phone Number',
    'forgotPassword': 'Forgot Password?',
    'pin': '6-Digit PIN',
    'pinRequired': 'Please enter your 6-digit PIN',
    'pinInvalid': 'PIN must be exactly 6 digits',
    'forgotPin': 'Forgot PIN?',
    'incorrectPin': 'The PIN you entered is incorrect.',
    'pinResetSuccess': 'PIN reset successfully!',
    'enterNewPin': 'Enter New PIN',
    'confirmNewPin': 'Confirm New PIN',
    'pinsDoNotMatch': 'PINs do not match',
    'resetPinBtn': 'Reset PIN',
    'dontHaveAccount': 'Don\'t have an account?',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccountSignUp': 'Don\'t have an account? Sign Up',
    'YouAlreadyHaveAccount? Log In': 'Already have an account? Log In',
    'youAlreadyHaveAccountLogin': 'Already have an account? Log In',
    'visitWebsite': 'Visit our website',
    'nameTooShort': 'Name must be at least 2 characters',
    'iAgreeTo': 'I agree to the',
    'privacyPolicyAndTerms': 'Privacy Policy & Terms',
    'mustAgreeToPolicies':
        'You must agree to the Privacy Policy & Terms to sign up',
    'agreeToTerms': 'I agree to the Terms of Service',
    'termsOfService': 'Terms of Service',
    'janeDoe': 'Jane Doe',
    'elevenDigits': '01#########',
    'lowestprice': 'Lowest Price',

    // Validation & Errors
    'enterValidEmail': 'Enter a valid email',
    'nameRequired': 'Please enter your name',
    'phoneRequired': 'Please enter your phone number',
    'fieldRequired': 'This field is required',
    'invalidAmount': 'Invalid amount',
    'amountMustBeGreater': 'Amount must be at least',
    'error': 'Error',
    'failed': 'Failed',

    // OTP Verification
    'verifyNumber': 'Verify Your Number',
    'enterCodeSentTo': 'Enter the code sent to',
    'verifyCodeBtn': 'Verify Code',

    // Home & Navigation
    'home': 'Home',
    'places': 'Places',
    'search': 'Search',
    'bookingHub': 'Booking Hub',

    'offers': 'Offers',
    'offer': 'Offer',
    'notifications': 'Notifications',
    'profile': 'Profile',

    // Owner Dashboard
    'ownerDashboard': 'Owner Dashboard',
    'addNewPlace': 'Add New Place',
    'myPlaces': 'My Places',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirmDeletion': 'Confirm Deletion',
    'areYouSureDelete': 'Are you sure you want to delete',

    'bookingsFor': 'Bookings for',
    'bookingDeletedSuccessfully': 'Booking deleted successfully.',

    'step_basic_info': 'Basic Information',
    'uploadMainPhotos': 'Upload Main Photos',
    'uploadSubPlacePhoto': 'Upload Field Photo',
    'addField': 'Add New Field',
    'photoRequired': 'Please add a photo for this field',
    'pressToSelectLocation': 'Press to select location on map',

    'errorSaving': 'Error occurred while saving: ',

    // Booking & Status
    'bookingPage': 'Booking Page',

    'selectDate': 'Select Date',
    'selectTime': 'Select Time',
    'selectDay': 'Select Day:',
    'availableTimeSlotsFor': 'Available Time Slots for ',
    'confirmAndBook': 'Confirm and Book',
    'confirmBooking': 'Confirm Booking',
    'notAvailableShort': 'N/A',
    'one_minute_to_pay': 'Slot temporarily locked for 1 minute to complete your booking.',
    'slot_taken_by_other': 'Sorry, this slot is temporarily locked by another user.',
    'ten_minutes_to_pay': 'Lock extended for 10 minutes to complete your payment.',
    'lock_expired': 'The temporary lock has expired. Please select the slot again.',
    'slot_busy_now': 'This slot is currently busy with a temporary lock. Try again later.',
    'in_process_yours': 'Locked by you',
    'in_process_other': 'Busy',
    'placePlaceholder': 'Place',
    'orderIdLabel': 'ID: #',
    'open': 'Open',
    'openClose': 'Open: %1 - Close: %2',
    'totalAmountColon': 'Total Amount: ',

    'newBooking': 'New Booking for Customer',
    'customerName': 'Customer Name',
    'selectedHours': 'Selected Hours',
    "myBookings": "My Bookings",
    "confirmed": "Confirmed",
    "pending": "Pending",
    "cancelled": "Cancelled",
    "paid": "Paid",
    "remaining": "Remaining",
    "total": "Total",
    "noBookingsFound": "No Bookings Found",
    "noBookingsSubtitle":
        "You haven't booked any matches or pitches yet. Start exploring and book your next slot!",
    "exploreNow": "Explore Now",
    "rebook": "Book Again",
    "fullyPaid": "Fully Paid",
    "depositPaid": "Deposit Paid",
    "totalPaid": "Total Paid",

    // PlaceModel Details
    'placeDetails': 'Place Details',
    'description': 'Description',
    'category': 'Category',
    'price': 'Price',
    'noPriceAvailable': 'No price available',
    'pricePerHour': 'Price per Hour',
    'pricePerHourColon': 'Price per Hour: ',
    'noPlayersInfo': 'No players info',
    'availableFields': 'Available fields',
    'viewDetails': 'View Details',
    'minimumCharge': 'Minimum Charge',
    'le': 'LE',
    'egp': 'LE',
    'about': 'About',
    'placeColon': 'Place: ',
    'sectionColon': 'Section: ',
    'playersColon': 'Players: ',

    // Payment Logic
    'bookingConfirmedSuccess':
        'Booking confirmed successfully! You can track your order status from the menu.',
    'confirmWalletPayment': 'Confirm Wallet Payment',
    'minimumDepositColon': 'Minimum Deposit Required: ',
    'failedPaymentUrl': 'Failed to prepare payment link',
    'errorProcessingPayment': 'Error processing payment',
    'minDeposit': 'Minimum',
    'halfAmount': 'Half Price',
    'fullPrice': 'Full Price',
    'enterPaymentAmount': 'Enter payment amount',
    'minimumRequiredDeposit': 'Minimum required deposit for booking',
    'remainingAmount': 'Remaining Amount',
    'customAmount': 'Custom Amount',
    'paymentAmount': 'Payment Amount',
    'selectPaymentAmount': 'Select payment amount',
    'enterAmount': 'Enter amount',
    'payViaWallet': 'Pay via Wallet',
    'allPaymentsMustBeDigital': 'All payments must be made digitally',
    'selectedAmount': 'Selected Amount',
    'customAmountPayment': 'Custom Amount Payment',

    // Categories
    'all': 'All',
    'football': 'Football',
    'padel': 'Padel',
    'playstation': 'PlayStation',
    'cafe': 'Cafe',

    'Football': 'Football',
    'PlayStation': 'PlayStation',
    'Cafe': 'Cafe',
    'Padel': 'Padel',

    // Week Days & Time
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'day': 'Day',
    'hour_singular': 'hour',
    'hour_plural': 'hours',
    'durationLabel': 'Duration',
    'summary_consecutive': 'You booked {} {} from {}:00 to {}:00 on {}',
    'summary_separate': 'You booked {} separate hours on {}:',
    'slot_prefix': 'Slot {}: From {}:00 to {}:00',

    // UI Actions
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'ok': 'OK',
    'save': 'Save',

    'noData': 'No data available.',

    "past_status": "Ended",
    "booked_by_app": "Booked by the app",
    "booked_by_you": "Booked by you",
    "available_status": "Available",
    "msg_time_started": "This time has already started",
    "msg_already_booked": "Sorry, this slot is already booked",
    "business_dashboard": "Business Dashboard",
    "app_deposits": "App Deposits",
    "app_work": "App Work",
    "manual_revenue": "Manual Revenue",
    "resv_count": "Resv. Count",
    "usage_performance": "Usage Performance",
    "hrs_unit": " Hrs",

    // Missing keys added during localization audit
    "originalTotal": "Original Total",
    "Pleaseenteryour": "Please enter your",
    "remainingForField": "Remaining for field",
    "requiredNow": "Required now",
    "resendAvailable": "Resend available",
    "resendCode": "Resend code",
    "resendIn": "Resend in",
    "revenue_split": "Revenue Split",
    "Signuptounlockallbookingopportunities.":
        "Sign up to unlock all booking opportunities.",
    "total_money__by_app": "Total money by app",
    "total_op_hours_desc": "Total operational hours description",
    "usePoints": "Use Points",
    "using": "Using",
    "viewOnMap": "View on Map",
    "openStatus": "Open Now",
    "closedStatus": "Closed",
    "willBepaid": "Will be paid",
    "confirmAccount": "Confirm Account",

    // Owner Onboarding
    "near": "Near",
    "filteredByAreaTime": "Filtered by location & hours",

    "selectAreaLabel": "Select Area",
    "filterPlacesTitle": "Area & Time Filters",
    "filterPlacesSubtitle": "Find places matching your specific needs",
    "searchRadiusLabel": "Search Radius",
    "chooseLocationOnMap": "Choose location on map...",
    "chooseBookingDate": "Tap to pick a day...",
    "targetDateLabel": "📅 When do you want to play?",
    "timeRangeLabel": "🕐 What time works for you?",
    "fromTimeLabel": "From",
    "clearBtn": "Clear",
    "searchBtn": "Set it Up",

    // Interactive Onboarding Guide
    "replayGuide": "Interactive Guide",

    "guide_bookings_title": "Your Booking History 📅",
    "guide_bookings_desc":
        "Manage your matches here. Scan the stadium's QR code (within 1km) to check in. If marked No-Show by mistake, click 'Verify GPS' inside the stadium to restore your status.",
    "guide_search_title": "Instant Search 🔍",
    "guide_search_desc":
        "Type the name or location of any pitch or place to filter venues immediately.",
    "guide_filters_desc":
        "Choose a target location, search radius, date, and hour duration to filter what's open instantly!",
    "guide_categories_title": "Sports & Mood Selector ⚽",
    "guide_categories_desc":
        "Choose categories like Football or Padel. The strategy board background will dynamically paint coordinates for your selection!",
    "guide_tabs_title": "Sort & Filters Quick Tabs 📑",
    "guide_tabs_desc":
        "Toggle between Nearby venues, Special Offers, and Lowest Price options to sort match pitches instantly!",
    "statistics": "Statistics",
    "fields": "fields",
    "calendarSchedule": "Manage Schedule",
    "app_vs_manual": "App vs Manual",
    "camera": "Camera",
    "cash_collected_by_you": "Cash collected by you",
    "gallery": "Gallery",
    "guide_logo_title": "👑",
    "guide_menu_title": "Settings & Account ⚙️",
    "hours_from_users": "Hours booked by users",
    "money_held_by_app": "Amounts in App Wallet",
    "showing_data_from": "Showing data from",
    "to": "to",
    "total_revenue_gross": "Total Gross Revenue",
    "tooManyRequests":
        "Whoa, slow down! 🛑\nYou've sent too many requests. Please wait 15 minutes before trying again.",
    "tooManyRequestsBlock":
        "Resend blocked due to too many attempts. Please try again later.",
    "noImage": "No image",
    "subplace_not_found": "Field/section not found",
    "no_schedule_available": "No schedule available for this field",
    "schedule_not_found": "Schedule not found",
    "user_not_authenticated": "User is not authenticated",
    "unknownPlace": "Unknown Place",
    "error_fetching_bookings": "Error fetching bookings",
    "failed_to_update_points": "Failed to update points",
    "failed_to_save_place": "Failed to save place data",
    "failed_to_update_place": "Failed to update place data",
    "failed_to_delete_place": "Failed to delete place completely",
    "failed_to_update_place_subplaces":
        "Failed to update place and fields data",
    "error_fetching_data": "An error occurred while fetching data.",
    "failed_to_add_place": "Failed to add place.",
    "failed_to_update_data": "Failed to update data.",
    "failed_to_load_analytics": "Failed to load analytics.",
    "failed_to_book_slots": "Failed to complete the booking.",
    "failed_to_fetch_your_places": "Failed to fetch your places.",
    "failed_to_load_global_dashboard": "Failed to load global dashboard data",
    "old_version_not_found_to_edit": "Old version not found to edit",
    "phoneNumberAlreadyExists":
        "This phone number is already registered. Try logging in instead.",
    "otpSendError":
        "Failed to send verification code. Please check your internet connection and try again.",
    "otpSessionExpired":
        "Session expired. Please request a new verification code.",
    "otpError":
        "The code you entered is incorrect or expired. Please try again.",
    'global_dashboard_title': 'Places Dashboard',
    'total_income': 'Total Income',
    'total_bookings': 'Total Bookings',
    'bookings_count_unit': 'Bookings',
    'places_performance_comparison': 'Places Comparison',
    'place_name_label': 'Name',
    'bookings_this_month': 'bookings this month',
    'cancellation_mode_active': 'Cancellation mode active',
    'clear_selection': 'Clear selection',
    'cancel_bookings': 'Cancel Bookings',
    'manual_booking': 'Manual Booking',
    'hour_selected_singular': 'hour selected',
    'hours_selected_plural': 'hours selected',
    'manage_bookings_and_fields': 'Manage Bookings & Fields',
    'field_label': 'Field',
    'chart_app_legend': 'App',
    'chart_manual_legend': 'Man.',
    "viewBookings": "View Bookings",
    "createManualBooking": "Create Manual Booking",
    "cancelBooking": "Cancel Bookings",
    "manageAvailability": "Manage Availability",
    "editPlaceInfo": "Edit Place Info",
    "viewAnalytics": "View Analytics",
    "manageEmployees": "Manage Employees",
    "managePlaces": "Manage Places",
    "searchByPhoneHint": "Search by phone number",
    "currentEmployeesTitle": "Current Employees",
    "searchResultsTitle": "Search Results",
    "noEmployeesFound": "No Employees Found",
    "manageEmployeesTitle": "Manage Employees",
    "edit_employee_dialog_assigned_places": "Assigned Places",
    "permissions": "Permissions",
    "booking_details_error": "Could not fetch booking details.",
    "booking_details_title": "Booking Details",
    "booker_name": "Booker Name",
    "booking_time": "Time Slot",
    "payment_method": "Payment Method",
    "payment_cash": "Cash",
    "payment_wallet": "Wallet / Online",
    "total_price": "Total Price",
    "paid_amount": "Amount Paid (Deposit)",
    "currency": "EGP",
    "contact_customer": "Contact Booker",
    "whatsapp": "WhatsApp",
    "call": "Call",
    "select_for_cancellation": "Select for Cancellation",
    "bookingRulesTitle": "Booking & Cancellation Policies",
    "bookingRulesSubtitle":
        "Please review and agree to the policies before confirming payment:",
    "ruleCancellation1":
        "• Cancellation > 6 hours before start: Refund minus 10 EGP admin fee.",
    "ruleCancellation2":
        "• Cancellation 2-6 hours before start: Penalty of 50% of deposit per 2-hour block closer to start + 10 EGP.",
    "ruleCancellation3":
        "• Cancellation < 2 hours before start: No refund (100% penalty).",
    "rulePenalty1":
        "• Level 1 User: Flexible payments enabled with normal deposit bounds.",
    "rulePenalty2":
        "• Level 2 User (1 No-Show): Flexible payments allowed but a 50 EGP fine is strictly added.",
    "rulePenalty3":
        "• Level 3 User (High Risk): Flexible payment disabled; must pay 100% price + 50 EGP fine online.",
    "agreeAndPay": "Agree & Pay",
    "cancelBtn": "Cancel",
    "confirmCancellation": "Confirm Cancellation",
    "cancel_success_msg":
        "Your booking was cancelled, and {} EGP was refunded to your wallet.",
    "cancel_error_msg":
        "Could not cancel booking, please check your connection.",
    "status_updated_successfully": "Status updated successfully.",
    "no_refund_requests": "No refund requests found.",
    "refund_requests_title": "Refund Requests",
    "all_requests": "All Requests",
    "requested_at": "Requested At",
    "approve": "Approve",
    "reject": "Reject",
    "processing": "Processing...",
    "no_show_success":
        "User marked as No Show successfully. 20 points deducted.",
    "no_show_error": "Failed to update user",
    "mark_no_show": "Mark No Show",
    "confirm_no_show_title": "Confirm No Show",
    "confirm_no_show_msg":
        "Are you sure you want to mark this booking as a No Show? This will deduct 20 points from the user and increment their penalty level.",
    "free_cancel_indicator":
        "Free cancellation minus 10 EGP admin fee for the next {} hours.",
    "penalty_cancel_indicator":
        "Cancellation penalty of 50% deposit now active.",
    "no_refund_indicator":
        "Ineligible for refund (match starts in less than 2 hours).",
    "upcoming_bookings_tab": "Upcoming Bookings",
    "refund_requests_tab": "Refund Requests",
    "refund_status_pending": "Pending Approval",
    "refund_status_approved": "Approved & Refunded",
    "refund_status_rejected": "Rejected",
    "original_paid": "Original Paid",
    "no_refund_requests_desc":
        "You do not have any refund requests at this time.",

    // Recent Updates & Missing Keys
    "cash_payment_warning":
        "Please pay the remaining amount in cash to the employee at the field, and show them the following verification PIN to confirm receipt.",
    "cash_pin_label": "Your verification PIN:",
    "dispute_no_show_title": "Are you actually at the field?",
    "dispute_no_show_desc":
        "The employee marked you as a No-Show. You can override this by verifying your GPS location within the venue boundaries.",
    "dispute_button": "Verify Attendance via GPS",
    "checking_gps": "Verifying location...",
    "dispute_consequences_title": "Confirm No-Show & Consequences",
    "gps_disabled_error": "Please enable GPS/Location services on your device.",
    "gps_permission_denied": "Location permission denied.",
    "gps_permission_denied_forever":
        "Location permissions are permanently disabled. Please enable them in your device settings.",
    "penalty_warning_title": "Warning: No-Show Policy ⚠️",
    "penalty_points_deduction":
        "• 20 points will be deducted from your balance immediately.",
    "penalty_l2_warning":
        "• This is your first infraction. A 50 EGP fine will be automatically added to your next booking.",
    "penalty_l3_warning":
        "• This is your second or higher infraction. Flexible payment options will be disabled; you must pay 100% online + 50 EGP fine in advance.",
    "admit_no_show_btn": "I admit No-Show and accept penalties",
    "admit_no_show_success":
        "Admitted successfully. Penalties applied and slot released.",
    "dispute_success_msg":
        "GPS verified successfully. Status reset to Attended.",
    "cash_collection_title": "Confirm Cash Receipt",
    "cash_collection_info":
        "Please enter the 4-digit PIN displayed on the customer's app to confirm cash collection.",
    "enter_pin_label": "Enter PIN",
    "pin_required_error": "PIN is required",
    "pin_length_error": "PIN must be exactly 4 digits",
    "invalid_cash_pin": "The entered PIN is incorrect. Please try again.",
    "cash_collected_success": "Cash collection confirmed successfully!",
    "no_show_locked_tooltip": "Locked until 50% of the match duration passes.",
    "status_pending_no_show": "Pending No-Show Verification",
    "status_attended": "Attended",
    "status_no_show": "No Show",
    "status_canceled": "Cancelled",
    "status_active": "Active",
    "msg_one_booking_at_a_time":
        "You can only select slots from one booking at a time.",
    "Active": "Active",
    "Add Place": "Add Place",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "EGP": "EGP",
    "Income": "Income",
    "Manage Auth": "Manage Permissions",
    "Mange Places": "Manage Places",
    "Offers": "Offers",
    "Owner not selected. Please go back to step 1.":
        "Owner not selected. Please go back to step 1.",
    "Places": "Places",
    "Please add at least one main photo": "Please add at least one main photo",
    "Please add at least one subplace": "Please add at least one field",
    "Please fill price and players for field":
        "Please fill price and players for field",
    "Please search and select an owner": "Please search and select an owner",
    "Please select a category": "Please select a category",
    "Promotions": "Promotions",
    "Refund Requests": "Refund Requests",
    "Save": "Save",
    "Searching ..": "Searching...",
    "Users": "Users",
    "Welcome": "Welcome",
    "activateDiscountHint": "Activate discount hint",
    "add": "Add",
    "addEmployeeTitle": "Add Employee",
    "app_revenue": "App Revenue",
    "approved": "Approved",
    "assignedPlaces": "Assigned Places",
    "closingTime": "Closing Time",
    "discount": "Discount",
    "edit_employee_dialog.no_places": "No places found to assign.",
    "languageSetting": "Language Settings",
    "manageAuthTitle": "Manage Permissions",
    "offerDiscount": "Offer Discount",
    "open24_7": "Open 24/7",
    "open24_7Subtitle": "This place is open all day every day",
    "openingTime": "Opening Time",
    "permission_denied": "Permission Denied",
    "place": "Place",
    "points": "Points",
    "rejected": "Rejected",
    "remove": "Remove",
    "username": "Username",
    "cash_pin_warning_text":
        "Please pay the remaining amount in cash to the employee at the field, and show them the following verification PIN to confirm receipt.",
    "checking_gps_progress": "Verifying your location via GPS...",
    "dispute_button_label": "Verify Attendance via GPS",
    "expectedRefund": "Expected Refund",
    "first_no_show_consequence":
        "This is your first infraction. A 50 EGP fine will be automatically added to your next booking.",
    "multi_no_show_consequence":
        "This is your second or higher infraction. Flexible payment options will be disabled; you must pay 100% online + 50 EGP fine in advance.",
    "pending_no_show_warning_body":
        "The employee marked you as a No-Show. You can override this by verifying your GPS location within the venue boundaries.",
    "pending_no_show_warning_title": "Are you actually at the field?",
    "checkIn": "Check In",
    "closeBtn": "Close",
    "confirm_cash_received_btn": "Confirm Cash Received",
    "current_points_label": "Your current points:",
    "dispute_too_far_title": "Dispute Failed: Distance Limit Exceeded",
    "expected_refund": "Expected Refund",
    "pay_rest_btn": "Pay Rest",
    "confirm_pay_rest_title": "Confirm Cash Payment",
    "confirm_pay_rest_msg":
        "Are you sure you want to confirm receipt of the remaining balance of {} EGP?",
    "remaining_payment_settled_success":
        "Remaining balance settled successfully!",
    "pay_online_btn": "Pay Online",
    "pay_cash_btn": "Pay Cash",
    "confirm_pay_cash_title": "Pay Cash at Field",
    "confirm_pay_cash_msg":
        "To pay the remaining balance in cash, a verification PIN will be generated. Please show this PIN to the employee at the field to confirm cash receipt. Generate PIN?",
    "cash_pin_created_title": "Verification PIN Generated",
    "cash_pin_created_desc":
        "Please pay the remaining amount in cash to the employee at the field, and show them this PIN code to confirm receipt:",
    "owner_pay_rest_pin_required":
        "Please ask the user to click 'Pay Rest' on their app to generate a cash verification PIN.",
    "search_bookings_hint": "Search by venue or court...",
    "sort_default": "Default Order",
    "sort_soonest": "Date: Soonest First",
    "sort_latest": "Date: Latest First",
    "sort_price_asc": "Price: Low to High",
    "sort_price_desc": "Price: High to Low",
    "filter_all": "All",
    "filter_active": "Active",
    "filter_attended": "Attended",
    "filter_canceled": "Canceled",
    "filter_no_show": "No-Show",
    "no_matching_bookings": "No bookings match your search.",
    "fully_paid_label": "Fully Paid",
    "unpaid_label": "Unpaid",
    "paid_label": "Paid",
    "remaining_label": "Remaining",
    "total_label": "Total",
    "governorate_cairo": "Cairo",
    "governorate_giza": "Giza",
    "governorate_alexandria": "Alexandria",
    "governorate_Damanhour": "Damanhour",
    "governorate_Beni Suef": "Beni Suef",
    "select_governorate": "Select Governorate",
  };
}
