class AppLocalizationsAr {
  static const Map<String, String> map = {
    // Auth & User Profile
    'appName': 'هنظبطهالك',
    'version': 'الإصدار',
    'login': 'تسجيل دخول',
    'signup': 'إنشاء حساب',
    'welcomeBack': 'يا تلتوميت ألف أهلاً',
    'email': 'الإيميل',
    'password': 'كلمة السر',
    'fullName': 'الاسم الكامل',
    'phoneNumber': 'الموبايل',
    'forgotPassword': 'نسيت كلمة السر؟',
    'pin': 'الرمز السري (PIN)',
    'pinRequired': 'برجاء إدخال الرمز السري (PIN)',
    'pinInvalid': 'الرمز السري يجب أن يكون ٦ أرقام بالظبط',
    'forgotPin': 'نسيت الرمز السري؟',
    'incorrectPin': 'الرمز السري الذي أدخلته غير صحيح.',
    'pinResetSuccess': 'تم إعادة تعيين الرمز السري بنجاح!',
    'enterNewPin': 'أدخل الرمز السري الجديد',
    'confirmNewPin': 'تأكيد الرمز السري الجديد',
    'pinsDoNotMatch': 'الرموز غير متطابقة',
    'resetPinBtn': 'إعادة تعيين الرمز السري',
    'dontHaveAccount': 'معندكش حساب؟',
    'alreadyHaveAccount': 'عندك حساب بالفعل؟',
    'dontHaveAccountSignUp': 'معندكش حساب؟ سجّل دلوقتي',
    'youAlreadyHaveAccountLogin': 'عندك حساب بالفعل؟ سجل دخول',
    'visitWebsite': 'زيارة موقعنا الإلكتروني',
    'nameTooShort': 'الاسم يجب أن يكون حرفين على الأقل',
    'iAgreeTo': 'أوافق على',
    'privacyPolicyAndTerms': 'سياسة الخصوصية والشروط والأحكام',
    'mustAgreeToPolicies':
        'يجب عليك الموافقة على سياسة الخصوصية والشروط لإنشاء الحساب',
    'agreeToTerms': 'أوافق على الشروط والأحكام',
    'termsOfService': 'الشروط والأحكام',
    'janeDoe': 'سليمان رجب',
    'elevenDigits': '01#################',
    'lowestprice': 'الاقل سعر ',

    // Validation & Errors
    'userNotFound': 'النمرة غلط يا عماد! \n الرقم ده مش متسجل',
    'wrongPassword': 'كلمة السر غلط.',
    'phoneNumberAlreadyExists':
        'الرقم ده مش غريب عليا \n الرقم ده متسجل قبل كدة',
    'weakPassword': 'الباسورد 🤏 (ضعيف جداً)',
    'invalidEmail': 'الإيميل غلط.',
    'emailRequired': 'نسيت الايميل خلي بالك !',
    'enterValidEmail': 'اكتب إيميل صحيح',
    'passwordRequired': 'نسيت تكتب الباسورد',
    'passwordMinLength': 'الباسورد لازم يكون ٨ حروف على الأقل',
    'nameRequired': 'برجاء إدخال الاسم',
    'phoneRequired': 'برجاء إدخال الرقم',
    'fieldRequired': 'الحقل ده مطلوب',
    'invalidAmount': 'المبلغ غير صحيح',
    'amountMustBeGreater': 'المبلغ يجب أن لا يقل عن',
    'error': 'حصل خطأ',
    'failed': 'فشلت العملية',
    'routeNotFound': 'احنا في عجيبة ايه الي وداك غريبة؟',

    // OTP Verification
    'verifyNumber': 'تحقق من رقمك',
    'enterCodeSentTo': 'أدخل الكود المرسل للرقم',
    'verifyCodeBtn': 'تأكيد الكود',
    'codeSentSuccess': 'تم إرسال الكود بنجاح',
    'invalid_otp': 'الكود غلط، حاول تاني',
    'session_expired': 'وقت الكود خلص، اطلب كود جديد',

    // Home & Navigation
    'home': 'الرئيسية',
    'places': 'الأماكن',
    'search': 'بحث',
    'bookingHub': 'مركز الحجز',
    'nearby': 'قريب منك',
    'offers': 'عروض',
    'offer': 'عرض',
    'notifications': 'الإشعارات',
    'profile': 'الملف الشخصي',
    'quickActions': 'الخيارات السريعة',

    // Owner Dashboard
    'ownerDashboard': 'لوحة التحكم للمالك',
    'addNewPlace': 'ضيف مكان جديد',
    'myPlaces': 'أماكني',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirmDeletion': 'تأكيد الحذف',
    'areYouSureDelete': 'متأكد إنك عايز تحذف المكان ده؟',
    'placeDeletedSuccessfully': 'المكان اتحذف بنجاح!',
    'noPlacesFound': 'مفيش أماكن موجودة.',
    'bookingsFor': 'الحجوزات لـ',
    'bookingDeletedSuccessfully': 'الحجز اتحذف بنجاح.',
    'errorDeletingPlace': 'فشل في حذف المكان، حاول مرة تانية',
    'step_basic_info': 'المعلومات الأساسية',
    'uploadMainPhotos': 'ارفع الصور الأساسية للمكان',
    'uploadSubPlacePhoto': 'صور الملعب',
    'addField': 'إضافة ملعب جديد',
    'photoRequired': 'يا ريت تختار صورة للملعب ده',
    'pressToSelectLocation': 'اضغط لتحديد الموقع على الخريطة',
    'locationSelectedSuccess': 'تم تحديد الموقع بنجاح ✅',
    'successTitle': 'تم الحفظ بنجاح!',
    'successDesc': 'مكانك دلوقتي على الخريطة وجاهز للحجز!',
    'successButton': 'تمام',
    'errorSaving': 'حصل خطأ أثناء الحفظ: ',

    // Booking & Status
    'bookingPage': 'صفحة الحجز',
    'bookNow': 'احجز دلوقتي',
    'available': 'متاح',
    'unavailable': 'مش متاح',
    'noSlotsAvailable': 'مفيش مواعيد متاحة',
    'selectDate': 'اختار التاريخ',
    'selectTime': 'اختار الوقت',
    'selectDay': 'اختار اليوم:',
    'availableTimeSlotsFor': 'المواعيد المتاحة ليوم ',
    'confirmAndBook': 'أكد واحجز',
    'confirmBooking': 'تأكيد الحجز',
    'notAvailableShort': 'غير متاح',
    'one_minute_to_pay': 'تم حجز الساعة مؤقتاً لمدة دقيقة واحدة لإتمام الحجز.',
    'slot_taken_by_other': 'عذراً، هذه الساعة محجوزة مؤقتاً من قبل مستخدم آخر.',
    'ten_minutes_to_pay': 'تم تمديد الحجز مؤقتاً لمدة ١٠ دقائق لإتمام عملية الدفع.',
    'lock_expired': 'انتهت صلاحية الحجز المؤقت. يرجى إعادة اختيار الساعة.',
    'slot_busy_now': 'هذه الساعة مشغولة بحجز مؤقت الآن. حاول لاحقاً.',
    'in_process_yours': 'حجزك المؤقت',
    'in_process_other': 'مشغول حالياً',
    'placePlaceholder': 'مكان',
    'orderIdLabel': 'رقم الطلب: #',
    'open': 'فاتح',
    'openClose': 'الفتح: %1 - الإغلاق: %2',
    'totalAmountColon': 'إجمالي الحساب: ',
    'pleaseSelectTimeSlot': 'الرجاء اختيار وقت للحجز أولاً',
    'newBooking': 'حجز جديد لعميل',
    'customerName': 'اسم العميل',
    'selectedHours': 'الساعات المختارة',
    "myBookings": "حجوزاتي",
    "confirmed": "مؤكد",
    "pending": "قيد الانتظار",
    "cancelled": "ملغي",
    "paid": "المدفوع",
    "remaining": "المتبقي",
    "total": "الإجمالي",
    "noBookingsFound": "لا توجد حجوزات",
    "noBookingsSubtitle":
        "لم تقم بحجز أي ملاعب أو مباريات بعد. ابدأ في استكشاف الملاعب واحجز مكانك الآن!",
    "exploreNow": "استكشف الآن",
    "rebook": "احجز مجدداً",
    "fullyPaid": "مدفوع بالكامل",
    "depositPaid": "عربون مدفوع",
    "totalPaid": "إجمالي المدفوع",
    "past": "المعاد ده عدا خلاص مش هنقدر نحجزه",
    "booked": "للاسف حد سبقك و حجز",

    // PlaceModel Details
    'placeDetails': 'تفاصيل المكان',
    'description': 'الوصف',
    'category': 'التصنيف',
    'price': 'السعر',
    'noPriceAvailable': 'السعر مش متاح حالياً',
    'pricePerHour': 'سعر الساعة',
    'pricePerHourColon': 'سعر الساعة: ',
    'noPlayersInfo': 'مش عارفين كام ضد كام',
    'availableFields': 'الملاعب المتاحة',
    'viewDetails': 'شوف التفاصيل',
    'minimumCharge': 'أقل مبلغ للحجز',
    'le': 'ج.م',
    'egp': 'ج.م',
    'about': 'عن المكان',
    'placeColon': 'المكان: ',
    'sectionColon': 'القسم: ',
    'playersColon': 'اللعيبة: ',

    // Payment Logic
    'paymentSuccess': 'عملية ناجحة!',
    'paymentFailed': 'فشلت العملية',
    'bookingConfirmedSuccess':
        'تم تأكيد الحجز بنجاح، تقدر تتابع حالة طلبك من القائمة.',
    'paymentFailedMessage':
        'للأسف حصل مشكلة أثناء الدفع، حاول تاني أو تواصل معنا.',
    'confirmWalletPayment': 'تأكيد دفع المحفظة',
    'minimumDepositColon': 'الحد الأدنى المطلوب: ',
    'failedPaymentUrl': 'فشل تجهيز رابط الدفع',
    'errorProcessingPayment': 'خطأ أثناء معالجة الدفع',
    'minDeposit': 'الحد الأدنى',
    'halfAmount': 'نص السعر',
    'fullPrice': 'السعر الكامل',
    'enterPaymentAmount': 'أدخل مبلغ الدفع',
    'minimumRequiredDeposit': 'الحد الأدنى المطلوب للحجز',
    'remainingAmount': 'المبلغ المتبقي',
    'customAmount': 'مبلغ مخصص',
    'paymentAmount': 'مبلغ الدفع',
    'selectPaymentAmount': 'اختر مبلغ دفع',
    'enterAmount': 'أدخل المبلغ',
    'payNow': 'ادفع الآن',
    'payViaWallet': 'الدفع عبر المحفظة',
    'secureDigitalPayment': 'دفع رقمي آمن',
    'allPaymentsMustBeDigital': 'جميع المدفوعات يجب أن تكون رقمية',
    'selectedAmount': 'المبلغ المختار',
    'customAmountPayment': 'دفع مبلغ مخصص',

    // Categories
    'all': 'الكل',
    'football': 'كرة قدم',
    'padel': 'بادل',
    'playstation': 'بلايستيشن',
    'cafe': 'كافيه / مطعم',
    'noPlacesInCategory': 'لا توجد أماكن في هذه الفئة حالياً',
    'Football': 'كرة قدم',
    'PlayStation': 'بلايستيشن',
    'Cafe': 'كافيه / مطعم',
    'Padel': 'بادل',

    // Week Days & Time
    'monday': 'الاثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    'sunday': 'الأحد',
    'day': 'اليوم',
    'hour_singular': 'ساعة',
    'hour_plural': 'ساعات',
    'durationLabel': 'مدة الحجز',
    'summary_consecutive': 'انت حجزت {} {} من الساعة {}:00 للساعة {}:00 يوم {}',
    'summary_separate': 'انت حجزت {} ساعات منفصلة يوم {}:',
    'slot_prefix': '• الساعة {}: من {}:00 لـ {}:00',

    // UI Actions
    'loading': 'جارِ التحميل...',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'ok': 'تمام',
    'save': 'حفظ',
    'logout': 'تسجيل خروج',
    'noData': 'مفيش بيانات.',
    'successMessage': 'تمت العملية بنجاح',
    'gallery': 'المعرض',
    'camera': 'الكاميرا',

    "past_status": "انتهى",
    "booked_by_app": "حجز بواسطة التطبيق",
    "booked_by_you": "حجزك أنت",
    "available_status": "متاح",
    "msg_time_started": "هذا الموعد قد بدأ بالفعل",
    "msg_already_booked": "عذراً، هذا الموعد محجوز مسبقاً",

    "business_dashboard": "لوحة تحكم النشاط",
    "showing_data_from": "عرض البيانات من",
    "to": "إلى",
    "total_revenue_gross": "إجمالي الإيرادات",
    "app_deposits": "عربون التطبيق",
    "money_held_by_app": "مبالغ في محفظة الأبلكيشن",
    "app_work": "شغل الأبلكيشن",
    "hours_from_users": "ساعات محجوزة من المستخدمين",
    "manual_revenue": "إيراد يدوي",
    "cash_collected_by_you": "كاش استلمته يدويًا",
    "resv_count": "عدد الحجوزات",
    "app_vs_manual": "التطبيق / يدوي",
    "usage_performance": "أداء الإشغال",
    "total_op_hours_desc": "إجمالي ساعات التشغيل في الفترة",
    "hrs_unit": " ساعة",

    // Missing keys added during localization audit
    "originalTotal": "الإجمالي الأصلي",
    "phoneInvalid": "الرقم ده ناقص",
    "place_not_found": "المكان غير موجود",
    "Pleaseenteryour": "يرجى إدخال",
    "remainingForField": "المتبقي للحقل",
    "requiredNow": "مطلوب الآن",
    "resendAvailable": "إعادة الإرسال متاحة",
    "resendCode": "إعادة إرسال الكود",
    "resendIn": "إعادة الإرسال خلال",
    "revenue_split": "تقسيم الإيرادات",
    "Signuptounlockallbookingopportunities.": "سجل لفتح جميع فرص الحجز.",
    "total_money__by_app": "إجمالي المال بواسطة التطبيق",
    "usePoints": "استخدام النقاط",
    "using": "استخدام",
    "viewOnMap": "عرض على الخريطة",
    "linkCopied": "تم نسخ رابط المكان إلى الحافظة!",
    "openStatus": "مفتوح الآن",
    "closedStatus": "مغلق حالياً",
    "willBepaid": "سيتم الدفع",
    "YouAlreadyHaveAccount? Log In": "عندك حساب بالفعل؟ سجل دخول",
    "confirmAccount": "بناكد الحساب",

    // Owner Onboarding
    "owner_intro_title": "شروط وسياسات المالك",
    "owner_intro_rules":
        "يرجى قراءة وفهم السياسات التالية:\n\n1. يجب أن تكون جميع معلومات الأماكن المسجلة صحيحة ودقيقة.\n2. يجب إدارة إلغاء الحجوزات وفقاً للتوجيهات المحددة.\n3. تتم معالجة المدفوعات الرقمية بشكل آمن من خلال المنصة.",
    "owner_agree_button": "أوافق على الشروط والأحكام",
    "owner_decline": "رفض",
    "owner_continue": "استمرار",
    "owner_pending_message":
        "حسابك حالياً في حالة مالك محدود (المالك ب).\n\nيمكنك تصفح الأماكن، ولكن لا يمكنك إضافة أو تعديل أي مكان حتى توافق على الشروط والأحكام.",

    // Catchy Map & Time Search Filter
    "catchyFilterTitle": "عندك خطة؟ هنظبطهالك حالا ⚡",
    "catchyFilterSubtitle": "اختار اليوم والوقت هنظبطلك كل الملاعب المتاحة",
    "smartFilterActiveTitle": "بنظبطهالك 😉....",
    "near": "بالقرب من",
    "filteredByAreaTime": "مظبوط حسب الموقع والساعات",
    "tryItBtn": "جربها!",
    "selectAreaLabel": "اختر المنطقة",
    "filterPlacesTitle": "معايير المنطقة والوقت",
    "filterPlacesSubtitle": "اعثر على الأماكن التي تطابق احتياجاتك المحددة",
    "searchRadiusLabel": "نطاق البحث",
    "chooseLocationOnMap": "اختر الموقع على الخريطة...",

    // Interactive Onboarding Guide
    "guide_skip": "انجزز",
    "guide_next": "ياعم عدي",
    "guide_back": "ارجعلي يابني",
    "guide_finish": "انطر ابلكاش",
    "replayGuide": "تعالي اخدك لفة ",
    "guide_welcome_title": "هنا هنظبطهالك ⚡",
    "guide_welcome_desc":
        "تعال ناخد لفة سريعة نعرفك فيها إزاي تلاقي وتحجز ملعبك المفضل في ثواني!",
    "guide_logo_title": "👑",
    "guide_logo_desc": "المكان و الوقت الي انت عايزه بالسعر الي انت  عايزه 😊",
    "guide_menu_title": "الإعدادات والحساب ⚙️",
    "guide_menu_desc": "اضغط هنا عشان تدخل على حسابك، تغير اللغة.",
    "guide_bookings_title": " شوف حجوزاتك 📅",
    "guide_bookings_desc":
        "إدارة مبارياتك من هنا. امسح كود الـ QR بالملعب (في نطاق 1كم) لإثبات الحضور. وإذا تم تسجيلك كغير حاضر بالخطأ، اضغط 'إثبات الحضور بالـ GPS' وأنت بالملعب لتعديل الحالة.",
    "guide_search_title": " دور علي اسم المكان🔍",
    "guide_search_desc":
        "اكتب اسم أو موقع أي ملعب أو مكان وهيظهرلك فوراً في ثواني معدودة.",
    "guide_filters_title": "اختار الي انت عايزه و متشلش هم⚡",
    "guide_filters_desc":
        "اضغط هنا عشان تدور بالخريطة، تحدد المسافة المناسبة ليك، اليوم، ومدة الحجز اللي عاوزها بالظبط واحنا هنظبطهالك .",
    "guide_categories_title": "لوحة الخطط التكتيكية ⚽",
    "guide_categories_desc":
        "اختار الفئة اللي حاببها، وهتلاقي خلفية التطبيق بتترسم تلقائياً بخطة الملعب المناسبة للي اخترته!",
    "guide_tabs_title": "تبويب الفرز السريع 📑",
    "guide_tabs_desc":
        "تقدر تتنقل بين الملاعب القريبة منك، العروض المميزة، أو الأقل سعراً عشان ترتب الملاعب حسب رغبتك فوراً!",
    "guide_firstCard_title": "احجز في ثواني! ⚡",
    "guide_firstCard_desc":
        "اضغط على أي ملعب لتحديد المواعيد وحجزها! يُفعل الحجز بعد الدفع. في حال دفع المتبقي نقداً، قم بتوليد كود (PIN) الخاص بك لإظهاره للموظف لتسوية المبلغ.",
    "statistics": "الإحصائيات",
    "fields": "ملاعب",
    "calendarSchedule": "جدول المواعيد",
    "chooseBookingDate": "اضغط عشان تختار اليوم...",
    "clearBtn": "مسح",
    "fromTimeLabel": "من",
    "searchBtn": "ظبطها",
    "targetDateLabel": "📅 حابب تلعب امتى؟",
    "timeRangeLabel": "🕐 الوقت المناسب ليك؟",
    "tooManyRequests":
        "براحة شوية! 🛑\nعملت محاولات كتير ورا بعض. استنى 15 دقيقة كدة وجرب تاني.",
    "tooManyRequestsBlock":
        "إرسال الكود مقفول بسبب محاولات كتير. جرب كمان شوية.",
    "noImage": "مفيش صورة",
    "subplace_not_found": "الملعب أو القسم غير موجود",
    "no_schedule_available": "لا يوجد جدول مواعيد لهذا الملعب!",
    "schedule_not_found": "جدول المواعيد غير موجود!",
    "user_not_authenticated": "المستخدم غير مسجل دخول",
    "unknownPlace": "مكان غير معروف",
    "error_fetching_bookings": "خطأ أثناء جلب الحجوزات",
    "failed_to_update_points": "فشل في تحديث النقاط",
    "failed_to_save_place": "فشل في حفظ بيانات المكان",
    "failed_to_update_place": "فشل في تحديث بيانات المكان",
    "failed_to_delete_place": "فشل في حذف المكان بالكامل",
    "failed_to_update_place_subplaces":
        "فشل في تحديث بيانات المكان والأماكن الفرعية",
    "error_fetching_data": "حدث خطأ أثناء جلب البيانات.",
    "failed_to_add_place": "فشل إضافة المكان.",
    "failed_to_update_data": "فشل تحديث البيانات.",
    "failed_to_load_analytics": "فشل تحميل التحليلات.",
    "failed_to_book_slots": "فشل تنفيذ عملية الحجز.",
    "failed_to_fetch_your_places": "فشل في جلب الأماكن الخاصة بك.",
    "failed_to_load_global_dashboard": "فشل في جلب بيانات لوحة التحكم العالمية",
    "old_version_not_found_to_edit": "النسخة القديمة غير موجودة لتعديلها",
    "otpSendError": "مش عارفين نبعت كود التحقق. اتأكد من النت وحاول تاني.",
    "otpSessionExpired": "وقت الجلسة انتهى. اطلب كود تحقق جديد.",
    "otpError": "الكود اللي دخلته غلط أو صلاحيته انتهت. حاول تاني.",
    'global_dashboard_title': 'لوحة تحكم الملاعب',
    'total_income': 'إجمالي الدخل',
    'total_bookings': 'إجمالي الحجوزات',
    'bookings_count_unit': 'حجز',
    'places_performance_comparison': 'مقارنة أداء الملاعب',
    'place_name_label': 'الاسم',
    'bookings_this_month': 'حجز هذا الشهر',
    'cancellation_mode_active': 'وضع الإلغاء نشط',
    'clear_selection': 'إلغاء التحديد',
    'cancel_bookings': 'إلغاء الحجوزات',
    'manual_booking': 'حجز يدوي',
    'hour_selected_singular': 'ساعة محددة',
    'hours_selected_plural': 'ساعات محددة',
    'manage_bookings_and_fields': 'إدارة الحجوزات والملاعب',
    'field_label': 'ملعب',
    'chart_app_legend': 'التطبيق',
    'chart_manual_legend': 'يدوي',

    "viewBookings": "عرض الحجوزات",
    "createManualBooking": "إنشاء حجز يدوي",
    "cancelBooking": "إلغاء الحجوزات",
    "manageAvailability": "إدارة المواعيد المتاحة",
    "editPlaceInfo": "تعديل بيانات الملعب",
    "viewAnalytics": "عرض التقارير والتحليلات",
    "manageEmployees": "إدارة الموظفين",
    "managePlaces": "إدارة الملاعب",
    "searchByPhoneHint": "ابحث برقم الموبايل",
    "currentEmployeesTitle": "الموظفين الحاليين",
    "searchResultsTitle": "نتائج البحث",
    "noEmployeesFound": "لا يوجد موظفين",
    "manageEmployeesTitle": "إدارة الموظفين",
    "edit_employee_dialog_assigned_places": "تعيين ملعب للموظف",
    "permissions": "الصلاحيات",
    "booking_details_error": "فشل في تحميل تفاصيل الحجز.",
    "booking_details_title": "تفاصيل الحجز",
    "booker_name": "اسم الحاجز",
    "booking_time": "موعد الحجز",
    "payment_method": "طريقة الدفع",
    "payment_cash": "نقداً",
    "payment_wallet": "المحفظة / الدفع الإلكتروني",
    "total_price": "السعر الإجمالي",
    "paid_amount": "المبلغ المدفوع (العربون)",
    "currency": "ج.م",
    "contact_customer": "التواصل مع الحاجز",
    "whatsapp": "واتساب",
    "call": "اتصال هاتفى",
    "select_for_cancellation": "تحديد للإلغاء",
    "bookingRulesTitle": "سياسات الحجز والإلغاء",
    "bookingRulesSubtitle":
        "برجاء مراجعة السياسات والموافقة عليها لإتمام عملية الدفع:",
    "ruleCancellation1":
        "• الإلغاء قبل أكثر من ٦ ساعات: استرداد المبلغ ناقص ١٠ جنيه رسوم إدارية.",
    "ruleCancellation2":
        "• الإلغاء بين ٦ و ٢ ساعة: خصم ٥٠٪ من قيمة العربون لكل ساعتين تقترب من موعد الحجز + ١٠ جنيه.",
    "ruleCancellation3":
        "• الإلغاء قبل أقل من ساعتين: لا يوجد استرداد (خصم ١٠٠٪).",
    "rulePenalty1":
        "• مستخدم مستوى ١: الدفع المرن متاح مع حدود العربون العادية.",
    "rulePenalty2":
        "• مستخدم مستوى ٢ (عدم حضور مرة): الدفع المرن متاح مع إضافة غرامة ٥٠ ج.م للحدود.",
    "rulePenalty3":
        "• مستخدم مستوى ٣ (مخالفات متكررة): الدفع المرن معطل؛ يجب دفع ١٠٠٪ من السعر + ٥٠ ج.م غرامة أونلاين.",
    "agreeAndPay": "موافق والدفع",
    "cancelBtn": "إلغاء",
    "confirmCancellation": "تأكيد إلغاء الحجز",
    "cancel_success_msg": "تم إلغاء حجزك بنجاح، وتمت استعادة {} ج.م لمحفظتك.",
    "cancel_error_msg": "تعذر إلغاء الحجز، يرجى التحقق من اتصالك بالإنترنت.",
    "status_updated_successfully": "تم تحديث الحالة بنجاح.",
    "no_refund_requests": "لا توجد طلبات استرداد حالياً.",
    "refund_requests_title": "طلبات الاسترداد",
    "all_requests": "كل الطلبات",
    "requested_at": "تاريخ الطلب",
    "approve": "قبول",
    "reject": "رفض",
    "processing": "جاري المعالجة...",
    "no_show_success": "تم تسجيل عدم الحضور بنجاح وخصم ٢٠ نقطة.",
    "no_show_error": "فشل تسجيل عدم الحضور للمستخدم",
    "mark_no_show": "تسجيل عدم حضور",
    "confirm_no_show_title": "تأكيد تسجيل عدم حضور",
    "confirm_no_show_msg":
        "هل أنت متأكد من تسجيل عدم حضور لهذا الحجز؟ سيتم خصم ٢٠ نقطة من المستخدم وزيادة مستوى العقوبة.",
    "free_cancel_indicator":
        "إلغاء مجاني ناقص ١٠ ج.م رسوم إدارية خلال الـ {} ساعات القادمة.",
    "penalty_cancel_indicator":
        "خصم ٥٠٪ غرامة إلغاء من قيمة العربون مطبق حالياً.",
    "no_refund_indicator":
        "غير قابل للاسترداد (المباراة تبدأ في أقل من ساعتين).",
    "upcoming_bookings_tab": "حجوزات قادمة",
    "refund_requests_tab": "طلبات الاسترداد",
    "refund_status_pending": "قيد الانتظار",
    "refund_status_approved": "تمت الموافقة والاسترداد",
    "refund_status_rejected": "مرفوض",
    "original_paid": "المدفوع الأصلي",
    "no_refund_requests_desc": "ليس لديك أي طلبات استرداد في الوقت الحالي.",

    // Recent Updates & Missing Keys
    "cash_payment_warning":
        "برجاء دفع المبلغ المتبقي نقداً للموظف بالملعب وإظهار كود التحقق التالي له لتأكيد الاستلام.",
    "cash_pin_label": "كود التحقق الخاص بك:",
    "dispute_no_show_title": "هل أنت بالملعب بالفعل؟",
    "dispute_no_show_desc":
        "لقد قام الموظف بتسجيلك كغير حاضر. يمكنك إثبات حضورك بالضغط أدناه وتأكيد موقعك الجغرافي (GPS) داخل حدود الملعب.",
    "dispute_button": "إثبات الحضور بالـ GPS",
    "checking_gps": "جاري التحقق من الموقع...",
    "dispute_consequences_title": "تأكيد عدم الحضور وعواقب الإجراء",
    "gps_disabled_error": "برجاء تشغيل تحديد الموقع (GPS) بالهاتف.",
    "gps_permission_denied": "تم رفض صلاحية استخدام الموقع.",
    "gps_permission_denied_forever":
        "صلاحيات الموقع معطلة تماماً. يرجى تفعيلها من إعدادات الهاتف.",
    "penalty_warning_title": "تحذير: سياسة عدم الحضور ⚠️",
    "penalty_points_deduction": "• سيتم خصم 20 نقطة من رصيدك فوراً.",
    "penalty_l2_warning":
        "• هذه هي مخالفتك الأولى. سيتم فرض غرامة قدرها 50 جنيه مصري تُضاف تلقائياً على حجزك القادم.",
    "penalty_l3_warning":
        "• هذه هي مخالفتك الثانية أو أكثر. سيتم إيقاف ميزة الدفع المرن لحسابك، ويتوجب عليك دفع 100% من قيمة الحجز القادم بالإضافة لغرامة 50 جنيه مقدماً أونلاين.",
    "admit_no_show_btn": "أقر بعدم الحضور وأقبل العقوبة",
    "admit_no_show_success":
        "تم تسجيل عدم حضورك وقبول العقوبة بنجاح، وتحرير الموعد.",
    "dispute_success_msg":
        "تم التحقق من الموقع الجغرافي بنجاح. تم تعديل الحالة إلى تم الحضور.",
    "cash_collection_title": "تأكيد استلام النقدية",
    "cash_collection_info":
        "يرجى إدخال الرمز المكون من 4 أرقام المعروض لدى العميل لتأكيد استلام المبلغ.",
    "enter_pin_label": "أدخل الرمز (PIN)",
    "pin_required_error": "الرمز مطلوب",
    "pin_length_error": "يجب أن يتكون الرمز من 4 أرقام",
    "invalid_cash_pin": "الرمز المدخل غير صحيح. يرجى المحاولة مجدداً.",
    "cash_collected_success": "تم تأكيد استلام النقدية بنجاح!",
    "no_show_locked_tooltip": "مغلق حتى يمر 50٪ من وقت الحجز.",
    "status_pending_no_show": "في انتظار إثبات الحضور",
    "status_attended": "تم الحضور",
    "status_no_show": "لم يحضر",
    "status_canceled": "ملغي",
    "status_active": "نشط",
    "msg_one_booking_at_a_time":
        "يمكنك اختيار مواعيد من حجز واحد فقط في المرة الواحدة.",
    "Active": "نشط",
    "Add Place": "إضافة مكان",
    "Cancel": "إلغاء",
    "Confirm": "تأكيد",
    "EGP": "ج.م",
    "Income": "الإيرادات",
    "Manage Auth": "إدارة الصلاحيات",
    "Mange Places": "إدارة الملاعب",
    "Offers": "العروض",
    "Owner not selected. Please go back to step 1.":
        "لم يتم اختيار المالك. يرجى العودة للخطوة الأولى.",
    "Places": "الملاعب",
    "Please add at least one main photo":
        "يرجى إضافة صورة رئيسية واحدة على الأقل",
    "Please add at least one subplace": "يرجى إضافة ملعب واحد على الأقل",
    "Please fill price and players for field":
        "يرجى كتابة السعر واللاعبين للملعب",
    "Please search and select an owner": "يرجى البحث واختيار مالك للملعب",
    "Please select a category": "يرجى اختيار فئة الملعب",
    "Promotions": "العروض والترويج",
    "Refund Requests": "طلبات الاسترداد",
    "Save": "حفظ",
    "Searching ..": "جاري البحث...",
    "Users": "المستخدمين",
    "Welcome": "مرحباً بك",
    "activateDiscountHint": "تفعيل تلميح الخصم",
    "add": "إضافة",
    "addEmployeeTitle": "إضافة موظف",
    "app_revenue": "إيرادات التطبيق",
    "approved": "مقبول",
    "assignedPlaces": "الملاعب المعينة",
    "closingTime": "وقت الإغلاق",
    "discount": "الخصم",
    "edit_employee_dialog.no_places": "لم يتم العثور على ملاعب لتعيينها.",
    "languageSetting": "إعدادات اللغة",
    "manageAuthTitle": "إدارة الصلاحيات",
    "offerDiscount": "خصم العرض",
    "open24_7": "مفتوح 24/7",
    "open24_7Subtitle": "هذا المكان مفتوح طوال اليوم كل يوم",
    "openingTime": "وقت الفتح",
    "permission_denied": "تم رفض الصلاحية",
    "place": "المكان",
    "points": "النقاط",
    "rejected": "مرفوض",
    "remove": "إزالة",
    "username": "اسم المستخدم",
    "emailAlreadyInUse": "هذا البريد الإلكتروني مسجل بالفعل لدينا.",
    "cash_pin_warning_text":
        "برجاء دفع المبلغ المتبقي نقداً للموظف بالملعب وإظهار كود التحقق التالي له لتأكيد الاستلام.",
    "checking_gps_progress": "جاري التحقق من موقعك بالـ GPS...",
    "dispute_button_label": "إثبات الحضور بالـ GPS",
    "expectedRefund": "المسترد المتوقع",
    "first_no_show_consequence":
        "هذه هي مخالفتك الأولى. سيتم فرض غرامة قدرها 50 جنيه مصري تُضاف تلقائياً على حجزك القادم.",
    "multi_no_show_consequence":
        "هذه هي مخالفتك الثانية أو أكثر. سيتم إيقاف ميزة الدفع المرن لحسابك، ويتوجب عليك دفع 100% من قيمة الحجز القادم بالإضافة لغرامة 50 جنيه مقدماً أونلاين.",
    "pending_no_show_warning_body":
        "لقد قام الموظف بتسجيلك كغير حاضر. يمكنك إثبات حضورك بالضغط أدناه وتأكيد موقعك الجغرافي (GPS) داخل حدود الملعب.",
    "pending_no_show_warning_title": "هل أنت بالملعب بالفعل؟",
    "checkIn": "تسجيل الحضور",
    "closeBtn": "إغلاق",
    "confirm_cash_received_btn": "تأكيد استلام النقدية",
    "current_points_label": "رصيد نقاطك الحالي:",
    "dispute_too_far_title": "فشل إثبات الحضور: تعديت حدود الملعب المسموح بها",
    "expected_refund": "المسترد المتوقع",
    "pay_rest_btn": "دفع المتبقي",
    "confirm_pay_rest_title": "تأكيد استلام المتبقي",
    "confirm_pay_rest_msg":
        "هل أنت متأكد من استلام المبلغ المتبقي وقدره {} ج.م؟",
    "remaining_payment_settled_success": "تم تسوية المبلغ المتبقي بنجاح!",
    "pay_online_btn": "دفع أونلاين",
    "pay_cash_btn": "دفع كاش",
    "confirm_pay_cash_title": "الدفع كاش بالملعب",
    "confirm_pay_cash_msg":
        "لدفع المبلغ المتبقي نقداً، سيتم إنشاء رمز تحقق. يرجى إظهار هذا الرمز للموظف بالملعب لتأكيد استلام المبلغ. هل تريد إنشاء الرمز؟",
    "cash_pin_created_title": "تم إنشاء رمز التحقق",
    "cash_pin_created_desc":
        "يرجى دفع المبلغ المتبقي نقداً للموظف بالملعب وإظهار رمز التحقق التالي له لتأكيد الاستلام:",
    "owner_pay_rest_pin_required":
        "يرجى الطلب من العميل الضغط على 'دفع المتبقي' في تطبيقه لتوليد رمز التحقق النقدي.",
    "search_bookings_hint": "ابحث عن الملعب أو الصالة...",
    "sort_default": "الترتيب الافتراضي",
    "sort_soonest": "التاريخ: الأقرب أولاً",
    "sort_latest": "التاريخ: الأحدث أولاً",
    "sort_price_asc": "السعر: من الأقل للأعلى",
    "sort_price_desc": "السعر: من الأعلى للأقل",
    "filter_all": "الكل",
    "filter_active": "نشط",
    "filter_attended": "تم الحضور",
    "filter_canceled": "ملغي",
    "filter_no_show": "لم يحضر",
    "no_matching_bookings": "لا توجد حجوزات تطابق بحثك.",
    "fully_paid_label": "مدفوع بالكامل",
    "unpaid_label": "غير مدفوع",
    "paid_label": "مدفوع",
    "remaining_label": "المتبقي",
    "total_label": "الإجمالي",
    "governorate_cairo": "القاهرة",
    "governorate_giza": "الجيزة",
    "governorate_alexandria": "الإسكندرية",
    "governorate_Damanhour": "دمنهور",
    "governorate_Beni Suef": "بني سويف",
    "select_governorate": "اختر المحافظة",
  };
}
